import { db } from "./db";
import { phrases } from "@shared/schema";

// New unique phrases from Surah Yusuf that are not yet in the database
const newYusufPhrases = [
  {
    arabicText: "أَحَبُّ إِلَىٰ أَبِينَا مِنَّا",
    englishTranslation: "More beloved to our father than us",
    surahAyah: "Yusuf 12:8",
    lifeApplication: "Expression of perceived unfairness in love or treatment. Used when feeling that someone shows favoritism towards another person.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "Recognition of jealousy and the need to address feelings of inequality",
    isPracticalDailyUse: 1,
    usageDomain: "family, emotions, fairness",
    register: "conversational",
  },
  {
    arabicText: "إِنَّ أَبَانَا لَفِي ضَلَالٍ مُّبِينٍ",
    englishTranslation: "Indeed, our father is in clear error",
    surahAyah: "Yusuf 12:8",
    lifeApplication: "Expression that someone close is making a clear mistake in judgment or dealing with a situation.",
    category: "short",
    difficulty: 3,
    symbolicMeaning: "Recognizing when loved ones make errors in judgment",
    isPracticalDailyUse: 1,
    usageDomain: "advice, disagreement, concern",
    register: "formal",
  },
  {
    arabicText: "اطۡرَحُوهُ أَرۡضًا",
    englishTranslation: "Cast him out to some distant land",
    surahAyah: "Yusuf 12:9",
    lifeApplication: "Metaphor for completely getting rid of someone or distancing them. Reflects the idea of total removal or exclusion.",
    category: "short",
    difficulty: 3,
    symbolicMeaning: "Warning against extreme solutions driven by jealousy",
    isPracticalDailyUse: 1,
    usageDomain: "conflict, exclusion, warning",
    register: "formal",
  },
  {
    arabicText: "يَخۡلُ لَكُمۡ وَجۡهُ أَبِيكُمۡ",
    englishTranslation: "The countenance of your father will be exclusively for you",
    surahAyah: "Yusuf 12:9",
    lifeApplication: "Desire to monopolize someone's attention, love, or favor - whether a parent, leader, or authority figure.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "Recognition of the human desire for exclusive attention and approval",
    isPracticalDailyUse: 1,
    usageDomain: "family, workplace, attention-seeking",
    register: "formal",
  },
  {
    arabicText: "قَوۡمٗا صَٰلِحِينَ",
    englishTranslation: "Righteous people",
    surahAyah: "Yusuf 12:9",
    lifeApplication: "Used to describe good, righteous people. A positive description of character.",
    category: "short",
    difficulty: 1,
    symbolicMeaning: "Aspiration towards righteousness and good character",
    isPracticalDailyUse: 1,
    usageDomain: "description, character, praise",
    register: "formal",
  },
  {
    arabicText: "لَا تَقۡتُلُواْ يُوسُفَ",
    englishTranslation: "Do not kill Yusuf",
    surahAyah: "Yusuf 12:10",
    lifeApplication: "Used to reject oppression or aggression against an innocent person. A call to protect the vulnerable.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "Standing against injustice and protecting the innocent",
    isPracticalDailyUse: 1,
    usageDomain: "justice, protection, advocacy",
    register: "formal",
  },
  {
    arabicText: "وَأَلۡقُوهُ فِي غَيَٰبَتِ ٱلۡجُبِّ",
    englishTranslation: "And throw him into the bottom of the well",
    surahAyah: "Yusuf 12:10, 12:15",
    lifeApplication: "Metaphor for hiding someone or something in a deep, concealed place. Used to describe concealment or suppression.",
    category: "short",
    difficulty: 3,
    symbolicMeaning: "Hidden problems or suppressed truths that will eventually surface",
    isPracticalDailyUse: 1,
    usageDomain: "concealment, secrets, suppression",
    register: "formal",
  },
  {
    arabicText: "يَلۡتَقِطۡهُ بَعۡضُ ٱلسَّيَّارَةِ",
    englishTranslation: "Some caravan will pick him up",
    surahAyah: "Yusuf 12:10",
    lifeApplication: "Suggestion that a stranger or unexpected person will find something/someone. Reminds us that relief can come from unexpected sources.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "Hope that strangers may be the means of relief and rescue",
    isPracticalDailyUse: 1,
    usageDomain: "hope, rescue, unexpected help",
    register: "formal",
  },
  {
    arabicText: "إِن كُنتُمۡ فَٰعِلِينَ",
    englishTranslation: "If you are to do [it]",
    surahAyah: "Yusuf 12:11",
    lifeApplication: "Conditional phrase questioning a group's intention to execute an idea. Used to challenge or confirm commitment.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "Testing commitment and sincerity in action",
    isPracticalDailyUse: 1,
    usageDomain: "challenge, commitment, questioning",
    register: "formal",
  },
  {
    arabicText: "يَٰٓأَبَانَا مَا لَكَ لَا تَأۡمَنَّا",
    englishTranslation: "O our father, why do you not trust us",
    surahAyah: "Yusuf 12:11",
    lifeApplication: "Expression of feeling hurt when someone doesn't trust you despite your love or good intentions.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "The pain of mistrust and the desire to prove oneself trustworthy",
    isPracticalDailyUse: 1,
    usageDomain: "family, trust, emotions",
    register: "conversational",
  },
  {
    arabicText: "وَإِنَّا لَهُۥ لَنَٰصِحُونَ",
    englishTranslation: "And indeed, we are his sincere well-wishers",
    surahAyah: "Yusuf 12:11",
    lifeApplication: "Affirmation of good intentions and sincere advice to someone who doubts you.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "Asserting sincerity when facing suspicion",
    isPracticalDailyUse: 1,
    usageDomain: "sincerity, trust, assurance",
    register: "formal",
  },
  {
    arabicText: "أَرۡسِلۡهُ مَعَنَا غَدٗا يَرۡتَعۡ وَيَلۡعَبۡ",
    englishTranslation: "Send him with us tomorrow that he may enjoy himself and play",
    surahAyah: "Yusuf 12:12",
    lifeApplication: "Request to let someone join you for leisure and play. Used when inviting someone for recreation.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "The importance of recreation and trust in relationships",
    isPracticalDailyUse: 1,
    usageDomain: "invitation, recreation, family",
    register: "conversational",
  },
  {
    arabicText: "وَإِنَّا لَهُۥ لَحَٰفِظُونَ",
    englishTranslation: "And indeed, we will be his guardians",
    surahAyah: "Yusuf 12:12",
    lifeApplication: "Promise to protect and preserve someone or something entrusted to you.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "Commitment to responsibility and trustworthiness",
    isPracticalDailyUse: 1,
    usageDomain: "promise, protection, responsibility",
    register: "formal",
  },
  {
    arabicText: "إِنِّي لَيَحۡزُنُنِيٓ أَن تَذۡهَبُواْ بِهِۦ",
    englishTranslation: "Indeed, it saddens me that you should take him",
    surahAyah: "Yusuf 12:13",
    lifeApplication: "Expression of deep sadness about being separated from someone you care about.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "Natural parental concern and fear of separation",
    isPracticalDailyUse: 1,
    usageDomain: "emotions, separation, concern",
    register: "formal",
  },
  {
    arabicText: "وَأَخَافُ أَن يَأۡكُلَهُ ٱلذِّئۡبُ",
    englishTranslation: "And I fear that a wolf should devour him",
    surahAyah: "Yusuf 12:13",
    lifeApplication: "Expression of specific fear about a particular danger threatening someone or something precious to you.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "Parental anxiety and protective instinct",
    isPracticalDailyUse: 1,
    usageDomain: "fear, protection, concern",
    register: "formal",
  },
  {
    arabicText: "وَنَحۡنُ عُصۡبَةٌ إِنَّآ إِذٗا لَّخَٰسِرُونَ",
    englishTranslation: "While we are a [strong] group? Indeed, we would then be losers",
    surahAyah: "Yusuf 12:14",
    lifeApplication: "Emphasis that your strong group cannot possibly fail or fall into such weakness.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "Overconfidence and the need for humility",
    isPracticalDailyUse: 1,
    usageDomain: "teamwork, confidence, challenge",
    register: "conversational",
  },
  {
    arabicText: "فَلَمَّا ذَهَبُواْ بِهِۦ",
    englishTranslation: "So when they took him away",
    surahAyah: "Yusuf 12:15",
    lifeApplication: "Used when recalling the moment someone left with others. Narrative phrase for storytelling.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "The beginning of a journey or trial",
    isPracticalDailyUse: 1,
    usageDomain: "storytelling, narrative, recollection",
    register: "formal",
  },
  {
    arabicText: "وَأَجۡمَعُوٓاْ أَن يَجۡعَلُوهُ فِي غَيَٰبَتِ ٱلۡجُبِّ",
    englishTranslation: "And they all agreed to put him into the bottom of the well",
    surahAyah: "Yusuf 12:15",
    lifeApplication: "Describes a deliberate collective plan to harm someone secretly. Summarizes hidden conspiracy.",
    category: "short",
    difficulty: 3,
    symbolicMeaning: "Warning against collective wrongdoing and secret plots",
    isPracticalDailyUse: 1,
    usageDomain: "conspiracy, warning, collective action",
    register: "formal",
  },
  {
    arabicText: "لَتُنَبِّئَنَّهُم بِأَمۡرِهِمۡ هَٰذَا",
    englishTranslation: "You will surely inform them of this affair of theirs",
    surahAyah: "Yusuf 12:15",
    lifeApplication: "Comfort that wrongdoers will eventually be confronted with the truth of their actions.",
    category: "short",
    difficulty: 3,
    symbolicMeaning: "Divine promise that truth will prevail",
    isPracticalDailyUse: 1,
    usageDomain: "justice, truth, consolation",
    register: "formal",
  },
  {
    arabicText: "وَجَآءُوٓ أَبَاهُمۡ عِشَآءٗ يَبۡكُونَ",
    englishTranslation: "And they came to their father at night, weeping",
    surahAyah: "Yusuf 12:16",
    lifeApplication: "Description of fake crying and pretense of grief. Used to describe theatrical sorrow.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "Warning against deception and false emotions",
    isPracticalDailyUse: 1,
    usageDomain: "deception, emotions, warning",
    register: "formal",
  },
  {
    arabicText: "إِنَّا ذَهَبۡنَا نَسۡتَبِقُ",
    englishTranslation: "Indeed, we went racing",
    surahAyah: "Yusuf 12:17",
    lifeApplication: "Used to describe participation in a race or competition. Can be literal or metaphorical.",
    category: "short",
    difficulty: 1,
    symbolicMeaning: "Innocent activities that can become excuses for negligence",
    isPracticalDailyUse: 1,
    usageDomain: "sports, competition, activities",
    register: "conversational",
  },
  {
    arabicText: "عِندَ مَتَٰعِنَا",
    englishTranslation: "With our possessions",
    surahAyah: "Yusuf 12:17",
    lifeApplication: "Description of something left near belongings or baggage.",
    category: "short",
    difficulty: 1,
    symbolicMeaning: "Negligence in guarding what is precious",
    isPracticalDailyUse: 1,
    usageDomain: "belongings, location, description",
    register: "conversational",
  },
  {
    arabicText: "فَأَكَلَهُ ٱلذِّئۡبُ",
    englishTranslation: "And a wolf devoured him",
    surahAyah: "Yusuf 12:17",
    lifeApplication: "Excuse used by liars for loss of something precious. A fabricated reason for disappearance.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "Classic false excuse and the consequences of deception",
    isPracticalDailyUse: 1,
    usageDomain: "excuses, deception, loss",
    register: "formal",
  },
  {
    arabicText: "وَمَآ أَنتَ بِمُؤۡمِنٖ لَّنَا وَلَوۡ كُنَّا صَٰدِقِينَ",
    englishTranslation: "And you would not believe us, even if we were truthful",
    surahAyah: "Yusuf 12:17",
    lifeApplication: "Expression that the other party will not believe you no matter what you say, even if you're telling the truth.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "The tragedy of broken trust",
    isPracticalDailyUse: 1,
    usageDomain: "trust, communication, frustration",
    register: "formal",
  },
  {
    arabicText: "وَجَآءُو عَلَىٰ قَمِيصِهِۦ بِدَمٖ كَذِبٖ",
    englishTranslation: "And they brought upon his shirt false blood",
    surahAyah: "Yusuf 12:18",
    lifeApplication: "Description of fabricated evidence used to cover a crime. Metaphor for false proof.",
    category: "short",
    difficulty: 3,
    symbolicMeaning: "Warning against manufacturing false evidence",
    isPracticalDailyUse: 1,
    usageDomain: "deception, evidence, crime",
    register: "formal",
  },
  {
    arabicText: "بَلۡ سَوَّلَتۡ لَكُمۡ أَنفُسُكُمۡ أَمۡرٗا",
    englishTranslation: "Rather, your souls have enticed you to something",
    surahAyah: "Yusuf 12:18, 12:83",
    lifeApplication: "Recognition that one's own self/desires have made evil seem attractive. Describes self-deception.",
    category: "short",
    difficulty: 3,
    symbolicMeaning: "The danger of following base desires",
    isPracticalDailyUse: 1,
    usageDomain: "self-reflection, temptation, psychology",
    register: "formal",
  },
  {
    arabicText: "فَصَبۡرٞ جَمِيلٞ",
    englishTranslation: "So patience is most fitting",
    surahAyah: "Yusuf 12:18, 12:83",
    lifeApplication: "Beautiful, dignified patience when facing calamity. A motto for accepting divine decree gracefully.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "The nobility of patience without complaint",
    isPracticalDailyUse: 1,
    usageDomain: "patience, coping, resilience",
    register: "formal",
  },
  {
    arabicText: "وَٱللَّهُ ٱلۡمُسۡتَعَانُ عَلَىٰ مَا تَصِفُونَ",
    englishTranslation: "And Allah is the One sought for help against what you describe",
    surahAyah: "Yusuf 12:18",
    lifeApplication: "Reliance on Allah when facing false accusations and lies. Used when unable to defend against slander.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "Trust in divine justice when human justice fails",
    isPracticalDailyUse: 1,
    usageDomain: "reliance, defense, accusations",
    register: "formal",
  },
  {
    arabicText: "وَجَآءَتۡ سَيَّارَةٞ",
    englishTranslation: "And there came a caravan",
    surahAyah: "Yusuf 12:19",
    lifeApplication: "Narrative phrase describing the arrival of travelers. Used in storytelling about journeys.",
    category: "short",
    difficulty: 1,
    symbolicMeaning: "Unexpected arrivals that change destiny",
    isPracticalDailyUse: 1,
    usageDomain: "storytelling, travel, arrival",
    register: "formal",
  },
  {
    arabicText: "فَأَدۡلَىٰ دَلۡوَهُۥ",
    englishTranslation: "And he let down his bucket",
    surahAyah: "Yusuf 12:19",
    lifeApplication: "Someone starting a simple task and discovering a great treasure. Metaphor for unexpected findings.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "Small actions leading to great discoveries",
    isPracticalDailyUse: 1,
    usageDomain: "discovery, action, fortune",
    register: "formal",
  },
  {
    arabicText: "يَٰبُشۡرَىٰ هَٰذَا غُلَٰمٞ",
    englishTranslation: "Good news! Here is a boy",
    surahAyah: "Yusuf 12:19",
    lifeApplication: "Exclamation of joy upon finding a child or receiving a new blessing. Expression of happy surprise.",
    category: "short",
    difficulty: 1,
    symbolicMeaning: "Joy at unexpected blessings",
    isPracticalDailyUse: 1,
    usageDomain: "celebration, joy, good news",
    register: "conversational",
  },
  {
    arabicText: "وَأَسَرُّوهُ بِضَٰعَةٗ",
    englishTranslation: "And they concealed him as merchandise",
    surahAyah: "Yusuf 12:19",
    lifeApplication: "Hiding someone's true identity and treating them as mere commodity. Dehumanization.",
    category: "short",
    difficulty: 3,
    symbolicMeaning: "Warning against reducing humans to objects",
    isPracticalDailyUse: 1,
    usageDomain: "deception, exploitation, trafficking",
    register: "formal",
  },
  {
    arabicText: "وَٱللَّهُ عَلِيمُۢ بِمَا يَعۡمَلُونَ",
    englishTranslation: "And Allah is Knowing of what they do",
    surahAyah: "Yusuf 12:19, and others",
    lifeApplication: "Reminder that Allah sees all actions. Used to affirm divine awareness and accountability.",
    category: "short",
    difficulty: 1,
    symbolicMeaning: "Divine omniscience and ultimate accountability",
    isPracticalDailyUse: 1,
    usageDomain: "awareness, accountability, faith",
    register: "formal",
  },
  {
    arabicText: "وَشَرَوۡهُ بِثَمَنۢ بَخۡسٖ",
    englishTranslation: "And they sold him for a reduced price",
    surahAyah: "Yusuf 12:20",
    lifeApplication: "Selling something precious for far less than its worth. Undervaluing talent or blessings.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "Warning against undervaluing precious gifts",
    isPracticalDailyUse: 1,
    usageDomain: "trade, value, exploitation",
    register: "formal",
  },
  {
    arabicText: "دَرَٰهِمَ مَعۡدُودَةٖ",
    englishTranslation: "A few dirhams",
    surahAyah: "Yusuf 12:20",
    lifeApplication: "Describes a very small amount of money. Used to emphasize triviality of payment.",
    category: "short",
    difficulty: 1,
    symbolicMeaning: "The insignificance of worldly gain compared to true worth",
    isPracticalDailyUse: 1,
    usageDomain: "money, value, description",
    register: "formal",
  },
  {
    arabicText: "وَكَانُواْ فِيهِ مِنَ ٱلزَّٰهِدِينَ",
    englishTranslation: "And they were, concerning him, of those content to sell",
    surahAyah: "Yusuf 12:20",
    lifeApplication: "People who squandered a great blessing because they didn't recognize its value.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "Warning against failing to recognize blessings",
    isPracticalDailyUse: 1,
    usageDomain: "appreciation, regret, value",
    register: "formal",
  },
  {
    arabicText: "كَمَآ أَتَمَّهَا عَلَىٰٓ أَبَوَيۡكَ مِن قَبۡلُ",
    englishTranslation: "As He completed it upon your forefathers before",
    surahAyah: "Yusuf 12:6",
    lifeApplication: "Recognition that Allah completes a series of blessings upon you as He did upon your ancestors.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "Continuity of divine favor across generations",
    isPracticalDailyUse: 1,
    usageDomain: "gratitude, family legacy, blessings",
    register: "formal",
  },
  {
    arabicText: "وَتَرَكۡنَا يُوسُفَ عِندَ مَتَٰعِنَا",
    englishTranslation: "And we left Yusuf with our possessions",
    surahAyah: "Yusuf 12:17",
    lifeApplication: "Negligence in guarding what was entrusted to you. Used to describe abandonment of responsibility.",
    category: "short",
    difficulty: 2,
    symbolicMeaning: "The consequences of negligence and broken trust",
    isPracticalDailyUse: 1,
    usageDomain: "responsibility, negligence, trust",
    register: "formal",
  },
  {
    arabicText: "لَتُنَبِّئَنَّهُم بِأَمۡرِهِمۡ هَٰذَا وَهُمۡ لَا يَشۡعُرُونَ",
    englishTranslation: "You will surely inform them of this affair while they perceive not",
    surahAyah: "Yusuf 12:15",
    lifeApplication: "Comfort that oppressors will one day learn the truth of their actions when they least expect it.",
    category: "short",
    difficulty: 3,
    symbolicMeaning: "Divine timing in revealing truth and delivering justice",
    isPracticalDailyUse: 1,
    usageDomain: "justice, consolation, truth",
    register: "formal",
  },
  {
    arabicText: "إِنَّ رَبَّكَ عَلِيمٌ حَكِيمٌ",
    englishTranslation: "Indeed, your Lord is Knowing and Wise",
    surahAyah: "Yusuf 12:6, 12:83, and others",
    lifeApplication: "Reminder of Allah's perfect knowledge and wisdom. Used to accept things beyond our understanding.",
    category: "short",
    difficulty: 1,
    symbolicMeaning: "Trust in divine wisdom beyond human comprehension",
    isPracticalDailyUse: 1,
    usageDomain: "faith, trust, acceptance",
    register: "formal",
  },
];

async function addYusufPhrasesToDatabase() {
  console.log("🌟 Adding new phrases from Surah Yusuf...");

  try {
    for (let i = 0; i < newYusufPhrases.length; i++) {
      const phrase = newYusufPhrases[i];
      await db.insert(phrases).values(phrase);
      console.log(`✓ Added phrase ${i + 1}/${newYusufPhrases.length}: ${phrase.arabicText}`);
    }

    console.log("\n✅ Successfully added all phrases!");
    console.log("📊 Summary:");
    console.log(`   - Total phrases added: ${newYusufPhrases.length}`);
    console.log(`   - All from Surah Yusuf (Joseph)`);
    console.log(`   - Themes: family relations, trust, deception, justice, patience, wisdom`);
    console.log(`   - These phrases enrich daily conversation with Quranic expressions`);
    
  } catch (error) {
    console.error("❌ Error adding phrases:", error);
    throw error;
  }
}

addYusufPhrasesToDatabase()
  .then(() => {
    console.log("✓ Script completed successfully!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Script failed:", error);
    process.exit(1);
  });
