import { db } from "./db";
import { questionBanks } from "@shared/schema";

// 50 questions about proper conduct, speech etiquette, and dignified behavior from Surah Luqman
const adabQuestions = [
  {
    theme: "المشي بهدوء والاعتدال",
    themeEnglish: "Walking with Modesty and Balance",
    description: "امشِ بهدوء بلا تكبر",
    tags: ["مشي", "تواضع", "اعتدال"],
    correctPhraseIds: ["وَاقْصِدْ فِي مَشْيِكَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "خفض الصوت",
    themeEnglish: "Lowering the Voice",
    description: "خفّض صوتك قليلًا",
    tags: ["صوت", "تواضع", "أدب"],
    correctPhraseIds: ["وَاغْضُضْ مِن صَوْتِكَ"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "المراقبة الذاتية",
    themeEnglish: "Self-Awareness and Accountability",
    description: "انتبه لتصرفاتك مهما كانت صغيرة",
    tags: ["مراقبة", "حساب", "مسؤولية"],
    correctPhraseIds: ["إِن تَكُ مِثْقَالَ حَبَّةٍ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "حسن الكلام",
    themeEnglish: "Good Speech and Kind Words",
    description: "تصرّف بأدب في كلامك",
    tags: ["كلام", "لطف", "أدب"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "عدم التعجرف",
    themeEnglish: "Avoiding Arrogance",
    description: "لا تكن متعجرفًا أمام الناس",
    tags: ["تواضع", "عدم تكبر", "احترام"],
    correctPhraseIds: ["وَلَا تُصَعِّرْ خَدَّكَ لِلنَّاسِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم الضوضاء",
    themeEnglish: "Avoiding Noise and Loud Speech",
    description: "لا تتحدث بصوت مزعج",
    tags: ["صوت", "أدب", "احترام"],
    correctPhraseIds: ["إِنَّ أَنكَرَ الْأَصْوَاتِ لَصَوْتُ الْحَمِيرِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "التوازن في المشي",
    themeEnglish: "Balanced Walking",
    description: "كن متوازنًا في مشيتك",
    tags: ["توازن", "اعتدال", "تواضع"],
    correctPhraseIds: ["وَاقْصِدْ فِي مَشْيِكَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم الاستعلاء",
    themeEnglish: "Humility and Not Being Arrogant",
    description: "لا ترَ نفسك أفضل من الناس",
    tags: ["تواضع", "احترام", "تعامل"],
    correctPhraseIds: ["إِنَّ اللَّهَ لَا يُحِبُّ كُلَّ مُخْتَالٍ فَخُورٍ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم الصراخ",
    themeEnglish: "Speaking Softly",
    description: "لا تصرخ عند الحديث",
    tags: ["صوت", "هدوء", "أدب"],
    correctPhraseIds: ["وَاغْضُضْ مِن صَوْتِكَ"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "اللطف في الحديث",
    themeEnglish: "Gentleness in Speech",
    description: "كن لطيفًا في حديثك",
    tags: ["لطف", "كلام", "أدب"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "عدم التكبر على الآخرين",
    themeEnglish: "Not Being Arrogant to Others",
    description: "لا تكن متكبرًا على الآخرين",
    tags: ["تواضع", "احترام", "أدب"],
    correctPhraseIds: ["وَلَا تَمْشِ فِي الْأَرْضِ مَرَحًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "المشي بثقة",
    themeEnglish: "Walking with Confidence",
    description: "امشِ بثقة دون غرور",
    tags: ["ثقة", "توازن", "أدب"],
    correctPhraseIds: ["وَاقْصِدْ فِي مَشْيِكَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم التفاخر",
    themeEnglish: "Not Boasting",
    description: "لا تتفاخر بكلامك",
    tags: ["تواضع", "فخر", "كلام"],
    correctPhraseIds: ["إِنَّ اللَّهَ لَا يُحِبُّ كُلَّ مُخْتَالٍ فَخُورٍ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم التكبر في المشي",
    themeEnglish: "Not Walking with Pride",
    description: "لا تتكبر في مشيتك",
    tags: ["تكبر", "تواضع", "مشي"],
    correctPhraseIds: ["وَلَا تَمْشِ فِي الْأَرْضِ مَرَحًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم الاستهزاء",
    themeEnglish: "Not Belittling Others",
    description: "لا تقلل من شأن الآخرين",
    tags: ["احترام", "استهزاء", "أدب"],
    correctPhraseIds: ["وَلَا تُصَعِّرْ خَدَّكَ لِلنَّاسِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "حسن السلوك",
    themeEnglish: "Good Conduct",
    description: "كن حسن السلوك",
    tags: ["سلوك", "أدب", "حسن"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "الحساب الدقيق",
    themeEnglish: "Precise Accountability",
    description: "راقب تصرفاتك دائمًا",
    tags: ["مراقبة", "حساب", "تصرفات"],
    correctPhraseIds: ["إِن تَكُ مِثْقَالَ حَبَّةٍ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "اختيار الكلام",
    themeEnglish: "Choosing Words Wisely",
    description: "اختر كلامك جيدًا",
    tags: ["كلام", "حكمة", "أدب"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم الصراخ والضوضاء",
    themeEnglish: "Not Shouting",
    description: "لا تكن شديد الصوت",
    tags: ["صوت", "هدوء", "أدب"],
    correctPhraseIds: ["وَاغْضُضْ مِن صَوْتِكَ"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "اللطف مع الجميع",
    themeEnglish: "Kindness to Everyone",
    description: "تعامل مع الجميع بلطف",
    tags: ["لطف", "احترام", "تعامل"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "عدم المبالغة في المشي",
    themeEnglish: "Moderate Walking",
    description: "لا تبالغ في المشي",
    tags: ["اعتدال", "توازن", "مشي"],
    correctPhraseIds: ["وَاقْصِدْ فِي مَشْيِكَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "الاعتدال في المشي",
    themeEnglish: "Moderation in Walking",
    description: "امشِ باعتدال",
    tags: ["اعتدال", "توازن", "سلوك"],
    correctPhraseIds: ["وَاقْصِدْ فِي مَشْيِكَ"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "الرفق في التعامل",
    themeEnglish: "Gentleness in Dealing with Others",
    description: "كن رفيقًا في تعاملك",
    tags: ["رفق", "لطف", "أدب"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم الصخب",
    themeEnglish: "Avoiding Loud Noise",
    description: "لا تكن صاخبًا في الأماكن العامة",
    tags: ["صخب", "أدب", "احترام"],
    correctPhraseIds: ["إِنَّ أَنكَرَ الْأَصْوَاتِ لَصَوْتُ الْحَمِيرِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم الفظاظة",
    themeEnglish: "Not Being Harsh",
    description: "لا تكن فظًّا في كلامك",
    tags: ["فظاظة", "لطف", "كلام"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "احترام الآخرين",
    themeEnglish: "Respecting Others",
    description: "تحدث باحترام",
    tags: ["احترام", "أدب", "كلام"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "خفض النبرة",
    themeEnglish: "Lowering Tone of Voice",
    description: "تكلّم بنبرة منخفضة",
    tags: ["صوت", "نبرة", "هدوء"],
    correctPhraseIds: ["وَاغْضُضْ مِن صَوْتِكَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم التكبر في السلوك",
    themeEnglish: "Humility in Behavior",
    description: "لا تكن متكبّرًا في سلوكك",
    tags: ["تكبر", "تواضع", "سلوك"],
    correctPhraseIds: ["إِنَّ اللَّهَ لَا يُحِبُّ كُلَّ مُخْتَالٍ فَخُورٍ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم الإكثار من الكلام",
    themeEnglish: "Not Speaking Too Much",
    description: "لا تتكلم كثيرًا في كل موضوع",
    tags: ["كلام", "حكمة", "أدب"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم الإزعاج",
    themeEnglish: "Not Being Annoying",
    description: "لا تكن مزعجًا",
    tags: ["إزعاج", "أدب", "احترام"],
    correctPhraseIds: ["إِنَّ أَنكَرَ الْأَصْوَاتِ لَصَوْتُ الْحَمِيرِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "الهدوء أثناء المشي",
    themeEnglish: "Remaining Calm While Walking",
    description: "حافظ على هدوئك عند المشي",
    tags: ["هدوء", "توازن", "مشي"],
    correctPhraseIds: ["وَاقْصِدْ فِي مَشْيِكَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم إيذاء الآخرين بالصوت",
    themeEnglish: "Not Hurting Others with Loud Voice",
    description: "لا تؤذِ الناس بصوتك",
    tags: ["صوت", "أذى", "أدب"],
    correctPhraseIds: ["وَاغْضُضْ مِن صَوْتِكَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم الظاهرية",
    themeEnglish: "Not Being Superficial",
    description: "لا تكن ظاهريًا فقط",
    tags: ["حقيقة", "صدق", "سلوك"],
    correctPhraseIds: ["وَلَا تَمْشِ فِي الْأَرْضِ مَرَحًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم التباهي في المشي",
    themeEnglish: "Not Walking Boastfully",
    description: "لا تمشِ بتباهٍ",
    tags: ["تباهي", "تواضع", "مشي"],
    correctPhraseIds: ["وَاغْضُضْ مِن صَوْتِكَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم الضحك بصوت عالي",
    themeEnglish: "Not Laughing Loudly",
    description: "لا تضحك بصوت عالٍ",
    tags: ["صوت", "ضحك", "أدب"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "احترام الآخرين في المجلس",
    themeEnglish: "Respecting Others in Gatherings",
    description: "احترم الآخرين في المجلس",
    tags: ["احترام", "مجلس", "أدب"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "الأدب الدائم",
    themeEnglish: "Constant Politeness",
    description: "كن مهذبًا دائمًا",
    tags: ["أدب", "هذب", "سلوك"],
    correctPhraseIds: ["وَلَا تَمْشِ فِي الْأَرْضِ مَرَحًا"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "عدم المقاطعة",
    themeEnglish: "Not Interrupting Others",
    description: "لا تتكلم فوق الآخرين",
    tags: ["مقاطعة", "استماع", "أدب"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "الوضوح دون فوضى",
    themeEnglish: "Being Clear Without Chaos",
    description: "كن واضحًا دون فوضى",
    tags: ["وضوح", "نظام", "كلام"],
    correctPhraseIds: ["إِنَّ أَنكَرَ الْأَصْوَاتِ لَصَوْتُ الْحَمِيرِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم إزعاج الناس بالكلام",
    themeEnglish: "Not Bothering People with Talk",
    description: "لا تزعج الناس بكلامك",
    tags: ["كلام", "إزعاج", "أدب"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "التصرف الطبيعي",
    themeEnglish: "Natural Behavior",
    description: "تصرف بشكل طبيعي",
    tags: ["طبيعة", "صدق", "سلوك"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم الفضول",
    themeEnglish: "Not Being Nosy",
    description: "لا تكن فضوليًا بكلامك",
    tags: ["فضول", "احترام", "أدب"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم الجدل الكثير",
    themeEnglish: "Avoiding Excessive Arguments",
    description: "لا تكثر الجدل",
    tags: ["جدل", "احترام", "كلام"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم الكلام السريع",
    themeEnglish: "Not Speaking Hastily",
    description: "لا تتكلم بسرعة",
    tags: ["سرعة", "تمهل", "كلام"],
    correctPhraseIds: ["وَاغْضُضْ مِن صَوْتِكَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "التمهل في الكلام",
    themeEnglish: "Speaking Deliberately",
    description: "تمهّل في كلامك",
    tags: ["تمهل", "هدوء", "كلام"],
    correctPhraseIds: ["وَاغْضُضْ مِن صَوْتِكَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم الحدة في الكلام",
    themeEnglish: "Not Speaking Sharply",
    description: "لا تتحدث بنبرة حادة",
    tags: ["حدة", "لطف", "كلام"],
    correctPhraseIds: ["وَاغْضُضْ مِن صَوْتِكَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم الصلابة في الكلام",
    themeEnglish: "Not Being Rigid in Speech",
    description: "لا تكن صلبًا في كلامك",
    tags: ["صلابة", "لطف", "كلام"],
    correctPhraseIds: ["وَاغْضُضْ مِن صَوْتِكَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "مراقبة نبرة الصوت",
    themeEnglish: "Monitoring Tone of Voice",
    description: "راقب نبرة صوتك",
    tags: ["نبرة", "صوت", "وعي"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "اختيار الوقت المناسب",
    themeEnglish: "Choosing the Right Time",
    description: "اختر وقت الحديث",
    tags: ["وقت", "حكمة", "كلام"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "جعل الكلام هادفًا",
    themeEnglish: "Making Speech Purposeful",
    description: "اجعل كلامك هادفًا",
    tags: ["هدف", "حكمة", "كلام"],
    correctPhraseIds: ["وَقُل لِلنَّاسِ حُسْنًا"],
    difficulty: 2,
    category: "thematic",
  },
];

async function addAdabQuestionsToDB() {
  console.log("📖 Adding 50 Adab (Conduct & Etiquette) Questions from Surah Luqman...");

  try {
    for (let i = 0; i < adabQuestions.length; i++) {
      const question = adabQuestions[i];
      await db.insert(questionBanks).values(question as any);
      console.log(`✓ Added question ${i + 1}/50: ${question.theme}`);
    }

    console.log("\n✅ Successfully added all Adab questions!");
    console.log("📊 Summary:");
    console.log(`   - Total questions added: ${adabQuestions.length}`);
    console.log(`   - Topics: Speech, Conduct, Etiquette, Walking, Humility, Respect`);
    console.log(`   - All linked to Quranic expressions from Surah Luqman`);
  } catch (error) {
    console.error("❌ Error adding questions:", error);
    throw error;
  }
}

addAdabQuestionsToDB()
  .then(() => {
    console.log("✓ Script completed successfully!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Script failed:", error);
    process.exit(1);
  });
