import { db } from "./db";
import { questionBanks } from "@shared/schema";

// 50 questions from Surah Al-Baqarah (2:67-73) with their Quranic answers
const baqarahQuestions = [
  {
    theme: "التكليف الإلهي والطاعة",
    themeEnglish: "Divine Commandment and Obedience",
    description: "تذكير النفس بأن الأمر من الله وليس رأي شخصي",
    tags: ["طاعة", "تكليف", "إيمان"],
    correctPhraseIds: ["ان الله يامركم ان تذبحوا بقرة"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "السخرية والاستهزاء",
    themeEnglish: "Mockery and Ridicule",
    description: "الرد على من يتعامل مع الكلام الجاد بسخرية",
    tags: ["سخرية", "جدية", "احترام"],
    correctPhraseIds: ["اتتخذنا هزوا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "اللجوء إلى الله من الجهل",
    themeEnglish: "Refuge in Allah from Ignorance",
    description: "الخوف من الانزلاق للسلوك الجاهل",
    tags: ["جهل", "معوذة", "حماية"],
    correctPhraseIds: ["اعوذ بالله ان اكون من الجاهلين"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "طلب التوضيح والتبيان",
    themeEnglish: "Seeking Clarification",
    description: "طلب العالم أن يدعو الله لتوضيح الأمر الملتبس",
    tags: ["سؤال", "توضيح", "دعاء"],
    correctPhraseIds: ["ادع لنا ربك يبين لنا ما هي"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "الوسطية في الحياة",
    themeEnglish: "Moderation in Life",
    description: "تربية النفس على اختيار الحل الوسط",
    tags: ["توازن", "وسطية", "اعتدال"],
    correctPhraseIds: ["بقرة لا فارض ولا بكر عوان بين ذلك"],
    difficulty: 3,
    category: "thematic",
  },
  {
    theme: "تنفيذ الأوامر الواضحة",
    themeEnglish: "Executing Clear Commands",
    description: "الرد على من يماطل في تنفيذ أوامر واضحة",
    tags: ["طاعة", "تنفيذ", "حسم"],
    correctPhraseIds: ["فافعلوا ما تؤمرون"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "معرفة التفاصيل قبل الالتزام",
    themeEnglish: "Knowing Details Before Commitment",
    description: "طلب معرفة تفاصيل الشيء قبل الإقدام عليه",
    tags: ["تفاصيل", "معرفة", "سؤال"],
    correctPhraseIds: ["ادع لنا ربك يبين لنا ما لونها"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "مدح الشيء الحسن",
    themeEnglish: "Praising the Good",
    description: "مدح شيء لونه مشرق مبهج",
    tags: ["جمال", "مدح", "لون"],
    correctPhraseIds: ["انها بقرة صفراء فاقع لونها تسر الناظرين"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "تشابه الخيارات",
    themeEnglish: "Confused Options",
    description: "حالة تشتت الخيارات التي تختلط الأمور معها",
    tags: ["ارتباك", "تشويش", "التباس"],
    correctPhraseIds: ["ان البقر تشابه علينا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "الاستهداء بالله",
    themeEnglish: "Seeking Allah's Guidance",
    description: "الرجاء من الله للهداية للقرار الأفضل",
    tags: ["هداية", "دعاء", "توفيق"],
    correctPhraseIds: ["وانا ان شاء الله لمهتدون"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "وصف الإنسان العزيز",
    themeEnglish: "Describing a Noble Person",
    description: "وصف إنسان عزيز لم يعتد على الذل",
    tags: ["عزة", "كرامة", "أنفة"],
    correctPhraseIds: ["انها بقرة لا ذلول"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "عدم الإسهام في العمارة",
    themeEnglish: "Not Contributing to Development",
    description: "وصف من لا يساهم في عمارة الأرض",
    tags: ["كسل", "بطالة", "عدم إنتاج"],
    correctPhraseIds: ["لا ذلول تثير الارض ولا تسقي الحرث"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "النية الخالصة",
    themeEnglish: "Pure Intention",
    description: "وصف نية أو صفقة أو علاقة خالصة لله",
    tags: ["نية", "إخلاص", "خالص"],
    correctPhraseIds: ["مسلمة لا شية فيها"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "الاعتراف بالحق",
    themeEnglish: "Admitting the Truth",
    description: "وصف من كان يجادل ثم يعترف بالحق",
    tags: ["انقياع", "حق", "اعتراف"],
    correctPhraseIds: ["الان جئت بالحق"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "التردد في التنفيذ",
    themeEnglish: "Hesitation in Execution",
    description: "وصف من قام بالواجب بعد طول تردد",
    tags: ["تردد", "بطء", "تنفيذ"],
    correctPhraseIds: ["فذبحوها وما كادوا يفعلون"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "الهروب من المسؤولية",
    themeEnglish: "Evading Responsibility",
    description: "تذكير من يهرب من الاعتراف بخطئه",
    tags: ["اعتذار", "مسؤولية", "لوم"],
    correctPhraseIds: ["واذ قتلتم نفسا فادارأتم فيها"],
    difficulty: 3,
    category: "thematic",
  },
  {
    theme: "كتمان الحقيقة",
    themeEnglish: "Concealing the Truth",
    description: "تذكير من يكتم حقيقة مؤلمة",
    tags: ["كتم", "سر", "حقيقة"],
    correctPhraseIds: ["والله مخرج ما كنتم تكتمون"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "الخطوات العلاجية",
    themeEnglish: "Therapeutic Steps",
    description: "عند تجربة علاج أو خطوة بها أمل",
    tags: ["علاج", "حل", "أمل"],
    correctPhraseIds: ["فقلنا اضربوه ببعضها"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "الإحياء بعد اليأس",
    themeEnglish: "Reviving After Despair",
    description: "عند مشاهدة إنسان يعود للحياة بعد يأس",
    tags: ["حياة", "أمل", "إحياء"],
    correctPhraseIds: ["كذلك يحيي الله الموتى"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "آيات الله",
    themeEnglish: "Signs of Allah",
    description: "تذكر النفس بآيات الله للتفكر",
    tags: ["تفكر", "آيات", "تدبر"],
    correctPhraseIds: ["يريكم اياته لعلكم تعقلون"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "التعقل والفهم",
    themeEnglish: "Understanding and Intellect",
    description: "تذكير بأن الهدف هو الفهم لا الحفظ",
    tags: ["فهم", "عقل", "تعقل"],
    correctPhraseIds: ["لعلكم تعقلون"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "أوامر الله الواضحة",
    themeEnglish: "Allah's Clear Commands",
    description: "تذكر النفس بأن الأمر من الله",
    tags: ["أمر", "الله", "طاعة"],
    correctPhraseIds: ["ان الله يامركم"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "البهجة والسرور",
    themeEnglish: "Joy and Delight",
    description: "وصف منظر يدخل السرور على القلوب",
    tags: ["فرح", "سرور", "بهجة"],
    correctPhraseIds: ["تسر الناظرين"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "الاختيار الوسط",
    themeEnglish: "Middle Ground Choice",
    description: "وصف حل ليس كبير ولا صغير",
    tags: ["توازن", "وسط", "اعتدال"],
    correctPhraseIds: ["لا فارض ولا بكر"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "خط الوسط",
    themeEnglish: "The Middle Path",
    description: "مبدأ في الحياة لاتباع الوسط",
    tags: ["وسطية", "توازن", "اعتدال"],
    correctPhraseIds: ["عوان بين ذلك"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "السؤال عن الحقيقة",
    themeEnglish: "Asking About Reality",
    description: "سؤال قصير عن حقيقة شيء",
    tags: ["سؤال", "حقيقة", "معرفة"],
    correctPhraseIds: ["ما هي"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "السؤال عن اللون",
    themeEnglish: "Asking About Color",
    description: "سؤال عن لون شيء ما",
    tags: ["لون", "سؤال", "وصف"],
    correctPhraseIds: ["ما لونها"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "طلب الدعاء",
    themeEnglish: "Asking for Supplication",
    description: "طلب من صاحب قلب صالح أن يدعو",
    tags: ["دعاء", "التماس", "طلب"],
    correctPhraseIds: ["ادع لنا ربك"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "التوضيح والبيان",
    themeEnglish: "Clarification and Explanation",
    description: "طلب توضيح حقيقة موقف أو نية",
    tags: ["توضيح", "بيان", "شرح"],
    correctPhraseIds: ["يبين لنا ما هي"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "وصف الخصائص",
    themeEnglish: "Describing Characteristics",
    description: "طلب توضيح صفة محددة في أمر",
    tags: ["خصائص", "صفات", "وصف"],
    correctPhraseIds: ["يبين لنا ما لونها"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "الأصفر المميز",
    themeEnglish: "Distinctive Yellow",
    description: "وصف شيء أصفر مميز",
    tags: ["لون", "أصفر", "وصف"],
    correctPhraseIds: ["انها بقرة صفراء"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "اللون الفاقع",
    themeEnglish: "Vivid Color",
    description: "وصف لون قوي واضح ملفت للنظر",
    tags: ["لون", "وضوح", "تميز"],
    correctPhraseIds: ["فاقع لونها"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "إثارة المشكلات",
    themeEnglish: "Stirring Up Troubles",
    description: "وصف من يثير المشكلات",
    tags: ["مشاكل", "فوضى", "تحريض"],
    correctPhraseIds: ["تثير الارض"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "عدم العطاء",
    themeEnglish: "Not Giving or Nourishing",
    description: "وصف من لا يعطي ولا يغذي من حوله",
    tags: ["كسل", "بخل", "عدم عطاء"],
    correctPhraseIds: ["ولا تسقي الحرث"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "الظلم للنفس",
    themeEnglish: "Wronging a Soul",
    description: "تذكير نفس بيوم ظلمت فيه شخصاً",
    tags: ["ظلم", "إثم", "ندم"],
    correctPhraseIds: ["واذ قتلتم نفسا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "تبادل الاتهامات",
    themeEnglish: "Trading Accusations",
    description: "وصف حالة تبادل الاتهامات",
    tags: ["اتهام", "نزاع", "خلاف"],
    correctPhraseIds: ["فادارأتم فيها"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "الأسرار المكتومة",
    themeEnglish: "Hidden Secrets",
    description: "تذكير بأن ما يُخفى سيظهر",
    tags: ["سر", "كتم", "انكشاف"],
    correctPhraseIds: ["ما كنتم تكتمون"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "إظهار المخفي",
    themeEnglish: "Revealing the Hidden",
    description: "تذكير من يظن أن ما يخفيه لن ينكشف",
    tags: ["انكشاف", "عدالة", "حقيقة"],
    correctPhraseIds: ["والله مخرج ما كنتم تكتمون"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "الخطوة العلاجية",
    themeEnglish: "Therapeutic Intervention",
    description: "اقتراح خطوة علاجية قد تكون سبباً في الحل",
    tags: ["علاج", "حل", "تدخل"],
    correctPhraseIds: ["اضربوه ببعضها"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "إحياء الموتى",
    themeEnglish: "Reviving the Dead",
    description: "جمع بين إحياء الموتى وإظهار الآيات",
    tags: ["إحياء", "آيات", "قدرة"],
    correctPhraseIds: ["يحيي الله الموتى ويريكم اياته لعلكم تعقلون"],
    difficulty: 3,
    category: "thematic",
  },
  {
    theme: "دور المربي",
    themeEnglish: "The Role of the Educator",
    description: "تذكير بدور المربي في نقل أمر الله",
    tags: ["تربية", "دعوة", "قيادة"],
    correctPhraseIds: ["واذ قال موسى لقومه"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "التضحية بالعادات السيئة",
    themeEnglish: "Sacrificing Bad Habits",
    description: "التضحية بعادة سيئة لله",
    tags: ["تضحية", "عادة", "إصلاح"],
    correctPhraseIds: ["ان الله يامركم ان تذبحوا بقرة"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "الانقياد لله",
    themeEnglish: "Submission to Allah",
    description: "وصف قلب أو نية منقادة لله",
    tags: ["انقياد", "تسليم", "طاعة"],
    correctPhraseIds: ["مسلمة"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "الخلو من الشبهات",
    themeEnglish: "Free from Defects",
    description: "وصف عمل أو نية خالية من الشبهات",
    tags: ["نقاء", "خلوص", "إخلاص"],
    correctPhraseIds: ["لا شية فيها"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "الاعتراف بعد الإنكار",
    themeEnglish: "Confession After Denial",
    description: "عندما يعترف خصم بالحقيقة بعد إنكار طويل",
    tags: ["اعتراف", "انقياع", "حق"],
    correctPhraseIds: ["قالوا الان جئت بالحق"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "التنفيذ المتردد",
    themeEnglish: "Reluctant Execution",
    description: "وصف من ينفذ الصواب وهو متردد جداً",
    tags: ["تردد", "بطء", "عدم رغبة"],
    correctPhraseIds: ["وما كادوا يفعلون"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "آيات الله الظاهرة",
    themeEnglish: "Clear Signs of Allah",
    description: "تذكير بآيات الله التي تراها",
    tags: ["آيات", "تدبر", "تفكر"],
    correctPhraseIds: ["ويريكم اياته"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "العقل والتفكر",
    themeEnglish: "Intellect and Reflection",
    description: "مبدأ عند كل موقف يحتاج لتشغيل العقل",
    tags: ["عقل", "تفكر", "تدبر"],
    correctPhraseIds: ["لعلكم تعقلون"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "علامات الله في الحياة",
    themeEnglish: "Allah's Signs in Life",
    description: "الشعور بأن الله يريك علامات لتستيقظ",
    tags: ["آيات", "إيقاظ", "انتباه"],
    correctPhraseIds: ["يريكم اياته لعلكم تعقلون"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "دعاء الهداية",
    themeEnglish: "Prayer for Guidance",
    description: "دعاء بالهداية عند الاحتيار بين طرق",
    tags: ["دعاء", "هداية", "توفيق"],
    correctPhraseIds: ["وانا ان شاء الله لمهتدون"],
    difficulty: 2,
    category: "thematic",
  },
];

async function addBaqarahQuestionsToDatabase() {
  console.log("🌟 Adding 50 questions from Surah Al-Baqarah...");

  try {
    for (let i = 0; i < baqarahQuestions.length; i++) {
      const question = baqarahQuestions[i];
      await db.insert(questionBanks).values(question as any);
      console.log(`✓ Added question ${i + 1}/50: ${question.theme}`);
    }

    console.log("\n✅ Successfully added all questions!");
    console.log("📊 Summary:");
    console.log(`   - Total questions added: ${baqarahQuestions.length}`);
    console.log(`   - All from Surah Al-Baqarah (2:67-73)`);
    console.log(`   - Themes: Divine commandment, obedience, moderation, guidance, patience, truth`);
    
  } catch (error) {
    console.error("❌ Error adding questions:", error);
    throw error;
  }
}

addBaqarahQuestionsToDatabase()
  .then(() => {
    console.log("✓ Script completed successfully!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Script failed:", error);
    process.exit(1);
  });
