import { db } from "./db";
import { conversationPrompts } from "@shared/schema";

// 26 multilingual exercises from Surah Al-Baqarah (Arabic, Turkish, Swahili, Indonesian, English)
const multilingualExercises = [
  {
    question: "اذكر جملة قرآنية تقولها معناها اتستهزي بي؟",
    questionAr: "اذكر جملة قرآنية تقولها معناها اتستهزي بي؟",
    questionTr: "Benimle alay mı ediyorsun? anlamına gelen bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoisema yenye maana ya: \"Je, unaninidhihaki?\"",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu ucapkan yang maknanya: \"Apakah kamu mengolok-olokku?\"",
    questionEn: "Mention a Qur'anic sentence you say whose meaning is: \"Are you mocking me?\"",
    suggestedVerse: "اتتخذنا هزوا",
    category: "daily_life",
    usageDomain: "response_to_mockery",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تقولها لتنفي انك جاهل",
    questionAr: "اذكر جملة قرآنية تقولها لتنفي انك جاهل",
    questionTr: "Cahil olmadığını ifade etmek için söylediğin bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoisema ili kukanusha kwamba wewe si mjinga.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu ucapkan untuk menafikan bahwa kamu bodoh.",
    questionEn: "Mention a Qur'anic sentence you say to deny that you are ignorant.",
    suggestedVerse: "اعوذ بالله ان اكون من الجاهلين",
    category: "self_worth",
    usageDomain: "self_protection",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تطلب من شخص ان يدعو لك",
    questionAr: "اذكر جملة قرآنية تطلب من شخص ان يدعو لك",
    questionTr: "Birinden senin için dua etmesini istediğinde söylediğin bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoisema unapomwomba mtu akuombee dua.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu ucapkan saat meminta seseorang mendoakanmu.",
    questionEn: "Mention a Qur'anic sentence you say when you ask someone to pray for you.",
    suggestedVerse: "ادع لنا",
    category: "requests",
    usageDomain: "asking_for_prayer",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تطلب من شخص ان ينفذ ما امرته به",
    questionAr: "اذكر جملة قرآنية تطلب من شخص ان ينفذ ما امرته به",
    questionTr: "Birine emrettiğin şeyi yerine getirmesini istediğinde söylediğin bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayomwambia mtu atekeleze ulichomuamuru.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu ucapkan ketika meminta seseorang melaksanakan apa yang kamu perintahkan.",
    questionEn: "Mention a Qur'anic sentence you say when you ask someone to carry out what you commanded.",
    suggestedVerse: "فافعلوا ما تؤمرون",
    category: "commands",
    usageDomain: "instruction",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تقولها عندما تسأل من امامك عن اللون الذي يريده",
    questionAr: "اذكر جملة قرآنية تقولها عندما تسأل من امامك عن اللون الذي يريده",
    questionTr: "Karşındakine hangi rengi istediğini sorarken kullandığın bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoisema unapomuuliza mtu rangi anayoitaka.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu ucapkan saat bertanya kepada orang di depanmu tentang warna yang ia inginkan.",
    questionEn: "Mention a Qur'anic sentence you say when you ask the person in front of you which color they want.",
    suggestedVerse: "ما لونها",
    category: "questions",
    usageDomain: "asking_about_attributes",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تقولها عند مدح شيء مشرق مبهج للنفس",
    questionAr: "اذكر جملة قرآنية تقولها عند مدح شيء مشرق مبهج للنفس",
    questionTr: "Parlak ve nefsi sevindiren bir şeyi överken söylediğin bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoisema unapoisifia kitu chenye mwangaza kinachofurahisha nafsi.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu ucapkan ketika memuji sesuatu yang cerah dan menyenangkan jiwa.",
    questionEn: "Mention a Qur'anic sentence you say when praising something bright and delightful to the soul.",
    suggestedVerse: "تسر الناظرين",
    category: "praise",
    usageDomain: "appreciation",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تقولها عندما ترجوا من الله ان يهديك لافضل قرار",
    questionAr: "اذكر جملة قرآنية تقولها عندما ترجوا من الله ان يهديك لافضل قرار",
    questionTr: "Allah'tan seni en hayırlı karara ulaştırmasını dilediğinde söylediğin bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoisema unapomtumaini Mwenyezi Mungu akuongoze kwenye uamuzi bora zaidi.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu ucapkan ketika berharap Allah membimbingmu pada keputusan yang terbaik.",
    questionEn: "Mention a Qur'anic sentence you say when you hope Allah will guide you to the best decision.",
    suggestedVerse: "وانا ان شاء الله لمهتدون",
    category: "guidance",
    usageDomain: "seeking_direction",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تستخدمها لوصف منتج جيد بلا عيوب بلا شوائب",
    questionAr: "اذكر جملة قرآنية تستخدمها لوصف منتج جيد بلا عيوب بلا شوائب",
    questionTr: "Kusursuz ve lekesiz iyi bir ürünü tarif etmek için kullandığın bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoitumia kuelezea bidhaa nzuri isiyo na dosari wala uchafu.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu gunakan untuk menggambarkan produk yang bagus tanpa cacat dan tanpa noda.",
    questionEn: "Mention a Qur'anic sentence you use to describe a good product with no defects and no impurities.",
    suggestedVerse: "مسلمة لا شية فيها",
    category: "quality",
    usageDomain: "describing_excellence",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تقولها عندما ترى شخصا كان يجادل ثم اخيرا يعترف بالحق",
    questionAr: "اذكر جملة قرآنية تقولها عندما ترى شخصا كان يجادل ثم اخيرا يعترف بالحق",
    questionTr: "Uzun süre tartışıp sonunda hakkı kabul eden birini gördüğünde söylediğin bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoisema unapoona mtu aliyekuwa akibishana kisha hatimaye anakiri haki.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu ucapkan ketika melihat seseorang yang dulu berdebat lalu akhirnya mengakui kebenaran.",
    questionEn: "Mention a Qur'anic sentence you say when you see someone who used to argue and finally admits the truth.",
    suggestedVerse: "الان جئت بالحق",
    category: "truth",
    usageDomain: "reconciliation",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تصف بها من قام بالواجب بعد طول تردد وبطء",
    questionAr: "اذكر جملة قرآنية تصف بها من قام بالواجب بعد طول تردد وبطء",
    questionTr: "Görevini uzun tereddüt ve yavaşlıktan sonra yerine getiren birini tarif etmek için kullandığın bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoitumia kumwelezea yule aliyeutekeleza wajibu baada ya kusita kwa muda mrefu na kwa upole.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu gunakan untuk menggambarkan orang yang menunaikan kewajiban setelah ragu lama dan sangat lambat.",
    questionEn: "Mention a Qur'anic sentence you use to describe someone who fulfilled their duty after long hesitation and slowness.",
    suggestedVerse: "وما كادوا يفعلون",
    category: "effort",
    usageDomain: "perseverance",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تذكر بها من يهرب من الاعتراف بخطئه ويلقي اللوم على غيره",
    questionAr: "اذكر جملة قرآنية تذكر بها من يهرب من الاعتراف بخطئه ويلقي اللوم على غيره",
    questionTr: "Hatasını kabul etmekten kaçıp suçu başkalarına atan birine hatırlattığın bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayomtumia kumkumbusha anayekimbia kukiri kosa lake na kuwalaumu wengine.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu gunakan untuk mengingatkan orang yang lari dari mengakui kesalahannya dan menyalahkan orang lain.",
    questionEn: "Mention a Qur'anic sentence you use to remind someone who runs away from admitting their mistake and blames others.",
    suggestedVerse: "فادارأتم فيها",
    category: "accountability",
    usageDomain: "blame",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تذكر بها من يكتم حقيقة مؤلمة ويظن انها لن تنكشف",
    questionAr: "اذكر جملة قرآنية تذكر بها من يكتم حقيقة مؤلمة ويظن انها لن تنكشف",
    questionTr: "Acı bir gerçeği gizleyip asla ortaya çıkmayacağını sanan birine hatırlattığın bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayomtumia kumkumbusha anayeficha ukweli mchungu akidhani hautafichuka.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu gunakan untuk mengingatkan orang yang menyembunyikan kebenaran yang menyakitkan dan mengira tidak akan terbongkar.",
    questionEn: "Mention a Qur'anic sentence you use to remind someone who hides a painful truth and thinks it will never be revealed.",
    suggestedVerse: "والله مخرج ما كنتم تكتمون",
    category: "truth",
    usageDomain: "warning",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تكتبها شعارا لتربية العقل على التفكير والتعقل",
    questionAr: "اذكر جملة قرآنية تكتبها شعارا لتربية العقل على التفكير والتعقل",
    questionTr: "Aklı düşünmeye ve sağduyuya alıştırmak için slogan olarak yazdığın bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoandika kama kaulimbiu ya kulea akili juu ya kufikiri na kutumia akili.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu tulis sebagai slogan untuk mendidik akal pada berpikir dan berakal sehat.",
    questionEn: "Mention a Qur'anic sentence you write as a slogan to train the mind in thinking and using reason.",
    suggestedVerse: "لعلكم تعقلون",
    category: "wisdom",
    usageDomain: "education",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تصف بها منظرا او موقفا يدخل السرور على القلوب",
    questionAr: "اذكر جملة قرآنية تصف بها منظرا او موقفا يدخل السرور على القلوب",
    questionTr: "Gönüllere sevinç veren bir manzarayı veya durumu tasvir etmek için kullandığın bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoitumia kuelezea mandhari au tukio linaloleta furaha katika nyoyo.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu gunakan untuk menggambarkan pemandangan atau situasi yang memasukkan kegembiraan ke dalam hati.",
    questionEn: "Mention a Qur'anic sentence you use to describe a scene or situation that brings joy to hearts.",
    suggestedVerse: "تسر الناظرين",
    category: "joy",
    usageDomain: "appreciation",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تجعلها مبدأ في حياتك لاتباع خط الوسط بين طرفين",
    questionAr: "اذكر جملة قرآنية تجعلها مبدأ في حياتك لاتباع خط الوسط بين طرفين",
    questionTr: "Hayatında iki uç arasında orta yolu takip etmek için ilke edindiğin bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoifanya kanuni maishani mwako ya kufuata njia ya kati kati ya pande mbili.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu jadikan prinsip hidup untuk mengikuti jalan tengah di antara dua sisi.",
    questionEn: "Mention a Qur'anic sentence you adopt as a principle in your life to follow the middle path between two sides.",
    suggestedVerse: "عوان بين ذلك",
    category: "balance",
    usageDomain: "moderation",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تستخدمها كسؤال قصير عن حقيقة شيء او شخص",
    questionAr: "اذكر جملة قرآنية تستخدمها كسؤال قصير عن حقيقة شيء او شخص",
    questionTr: "Bir şeyin veya kişinin hakikatini sormak için kullandığın kısa bir Kur'an sorusu söyle.",
    questionSw: "Taja sentensi fupi ya Qur'ani unayoitumia kama swali kuhusu hakika ya jambo au mtu.",
    questionId: "Sebutkan satu kalimat pendek dari Al-Qur'an yang kamu gunakan sebagai pertanyaan tentang hakikat suatu hal atau seseorang.",
    questionEn: "Mention a short Qur'anic sentence you use as a question about the reality of something or someone.",
    suggestedVerse: "ما هي",
    category: "questions",
    usageDomain: "inquiry",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تستخدمها للسؤال عن لون شيء ما",
    questionAr: "اذكر جملة قرآنية تستخدمها للسؤال عن لون شيء ما",
    questionTr: "Bir şeyin rengini sormak için kullandığın bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoitumia kuuliza kuhusu rangi ya kitu fulani.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu gunakan untuk bertanya tentang warna suatu benda.",
    questionEn: "Mention a Qur'anic sentence you use to ask about the color of something.",
    suggestedVerse: "ما لونها",
    category: "questions",
    usageDomain: "inquiry",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تقولها عندما تطلب من صاحب قلب صالح ان يدعو لكم",
    questionAr: "اذكر جملة قرآنية تقولها عندما تطلب من صاحب قلب صالح ان يدعو لكم",
    questionTr: "Kalbi salih birinden sizin için dua etmesini istediğinde söylediğin bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoisema unapomuomba mtu wa moyo mwema awaombee nyinyi.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu ucapkan saat meminta orang berhati baik mendoakan kalian.",
    questionEn: "Mention a Qur'anic sentence you say when you ask someone with a righteous heart to pray for you (all).",
    suggestedVerse: "ادع لنا",
    category: "requests",
    usageDomain: "asking_for_prayer",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تعبر بها عن لون قوي واضح ملفت للنظر",
    questionAr: "اذكر جملة قرآنية تعبر بها عن لون قوي واضح ملفت للنظر",
    questionTr: "Güçlü, belirgin ve dikkat çekici bir rengi ifade etmek için kullandığın bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoitumia kuelezea rangi yenye nguvu, iliyo wazi na inayovutia macho.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu gunakan untuk mengekspresikan warna yang kuat, jelas, dan mencolok.",
    questionEn: "Mention a Qur'anic sentence you use to express a strong, clear, eye-catching color.",
    suggestedVerse: "فاقع لونها",
    category: "description",
    usageDomain: "color",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية يمكن ان تستخدمها للسؤال عما تخفون",
    questionAr: "اذكر جملة قرآنية يمكن ان تستخدمها للسؤال عما تخفون",
    questionTr: "Gizledikleriniz hakkında soru sormak için kullanılabilecek bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani inayoweza kutumika kuuliza kuhusu mnachokificha.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang bisa digunakan untuk bertanya tentang apa yang kalian sembunyikan.",
    questionEn: "Mention a Qur'anic sentence that can be used to ask about what you are hiding.",
    suggestedVerse: "ما كنتم تكتمون",
    category: "truth",
    usageDomain: "inquiry",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تقولها لجماعة ليضربوا شخصا",
    questionAr: "اذكر جملة قرآنية تقولها لجماعة ليضربوا شخصا",
    questionTr: "Bir topluluğa bir kişiyi vurmalarını söylemek için kullandığın bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoisema kwa kundi ukiwaamuru wampige mtu.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu ucapkan kepada sekelompok orang untuk memukul seseorang.",
    questionEn: "Mention a Qur'anic sentence you say to a group, telling them to strike a person.",
    suggestedVerse: "اضربوه",
    category: "commands",
    usageDomain: "instruction",
    isPracticalDailyUse: 0,
  },
  {
    question: "اذكر جملة او كلمة قرآنية تصف بها منتجا جيدا",
    questionAr: "اذكر جملة او كلمة قرآنية تصف بها منتجا جيدا",
    questionTr: "İyi bir ürünü tarif etmek için kullandığın bir Kur'an kelimesi veya cümlesi söyle.",
    questionSw: "Taja neno au sentensi ya Qur'ani unayoitumia kuelezea bidhaa nzuri.",
    questionId: "Sebutkan satu kata atau kalimat Al-Qur'an yang kamu gunakan untuk menggambarkan produk yang bagus.",
    questionEn: "Mention a Qur'anic word or sentence you use to describe a good product.",
    suggestedVerse: "مسلمة",
    category: "quality",
    usageDomain: "describing_excellence",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تصف بها منتجا خاليا من الشبهات والعيوب",
    questionAr: "اذكر جملة قرآنية تصف بها منتجا خاليا من الشبهات والعيوب",
    questionTr: "Şüphe ve kusurlardan tamamen uzak bir ürünü tarif etmek için kullandığın bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoitumia kuelezea bidhaa isiyo na mashaka wala dosari.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu gunakan untuk menggambarkan produk yang bebas dari syubhat dan cacat.",
    questionEn: "Mention a Qur'anic sentence you use to describe a product free of doubts and defects.",
    suggestedVerse: "لا شية فيها",
    category: "quality",
    usageDomain: "describing_excellence",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تقولها عندما يعترف خصم او شريك اخيرا بالحقيقة بعد انكار طويل",
    questionAr: "اذكر جملة قرآنية تقولها عندما يعترف خصم او شريك اخيرا بالحقيقة بعد انكار طويل",
    questionTr: "Uzun inkârdan sonra nihayet gerçeği itiraf eden bir rakip veya ortak olduğunda söylediğin bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoisema adui au mshirika anapokiri ukweli baada ya muda mrefu wa kukanusha.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu ucapkan ketika lawan atau rekan akhirnya mengakui kebenaran setelah lama mengingkari.",
    questionEn: "Mention a Qur'anic sentence you say when an opponent or partner finally admits the truth after a long denial.",
    suggestedVerse: "الان جئت بالحق",
    category: "truth",
    usageDomain: "reconciliation",
    isPracticalDailyUse: 1,
  },
  {
    question: "اذكر جملة قرآنية تصف بها من ينفذ الصواب وهو متردد وبطيء جدا",
    questionAr: "اذكر جملة قرآنية تصف بها من ينفذ الصواب وهو متردد وبطيء جدا",
    questionTr: "Doğruyu yapan ama çok tereddütlü ve aşırı yavaş olan birini tarif etmek için kullandığın bir Kur'an cümlesi söyle.",
    questionSw: "Taja sentensi ya Qur'ani unayoitumia kumwelezea anayefanya jambo sahihi huku akisita sana na kuwa wa polepole mno.",
    questionId: "Sebutkan satu kalimat Al-Qur'an yang kamu gunakan untuk menggambarkan orang yang melakukan hal yang benar tetapi sangat ragu dan sangat lambat.",
    questionEn: "Mention a Qur'anic sentence you use to describe someone who does the right thing but is very hesitant and very slow.",
    suggestedVerse: "وما كادوا يفعلون",
    category: "effort",
    usageDomain: "perseverance",
    isPracticalDailyUse: 1,
  },
];

async function addMultilingualExercisesToDatabase() {
  console.log("🌍 Adding 26 multilingual exercises from Surah Al-Baqarah...");

  try {
    let addedCount = 0;
    for (let i = 0; i < multilingualExercises.length; i++) {
      const exercise = multilingualExercises[i];
      await db.insert(conversationPrompts).values({
        question: exercise.question,
        questionEn: exercise.questionEn,
        questionTr: exercise.questionTr,
        questionSw: exercise.questionSw,
        questionId: exercise.questionId,
        suggestedVerse: exercise.suggestedVerse,
        category: exercise.category,
        usageDomain: exercise.usageDomain,
        isPracticalDailyUse: exercise.isPracticalDailyUse,
      } as any);
      addedCount++;
      console.log(`✓ Added exercise ${i + 1}/26: ${exercise.category}`);
    }

    console.log("\n✅ Successfully added all multilingual exercises!");
    console.log("📊 Summary:");
    console.log(`   - Total exercises added: ${addedCount}`);
    console.log(`   - Languages: Arabic, Turkish, Swahili, Indonesian, English`);
    console.log(`   - Source: Surah Al-Baqarah (2:67-73)`);
    console.log(`   - Categories: Commands, Quality, Guidance, Wisdom, Truth, Balance, Description, Joy, Effort, Requests, Accountability`);
  } catch (error) {
    console.error("❌ Error adding exercises:", error);
    throw error;
  }
}

addMultilingualExercisesToDatabase()
  .then(() => {
    console.log("\n✓ Script completed successfully!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Script failed:", error);
    process.exit(1);
  });
