import { db } from "./db";
import { questionBanks } from "@shared/schema";

// 100 Quranic vocabulary and expression questions
const vocabularyQuestions = [
  // Group 1: Surah Yusuf specific expressions (Questions 1-40)
  {
    theme: "الإساءة إلى الأهل",
    themeEnglish: "Harming One's Family",
    description: "تعبير قرآني عن من يريد الإساءة إلى أهل شخص ما",
    tags: ["يوسف", "عائلة", "إساءة"],
    correctPhraseIds: ["يريد ان يسيء الى اهلك"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "العقاب بالحبس",
    themeEnglish: "Punishment by Imprisonment",
    description: "الجملة القرآنية التي تعبر عن العقاب بالسجن",
    tags: ["يوسف", "عقاب", "سجن"],
    correctPhraseIds: ["يعاقب بالحبس"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الاستدراج للخطيئة",
    themeEnglish: "Tempting Towards Sin",
    description: "محاولة استدراج شخص ما لمخالفة أوامر الله",
    tags: ["يوسف", "إغواء", "خطيئة"],
    correctPhraseIds: ["حاولت ان تستدرجني"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الشاهد العادل",
    themeEnglish: "Just Witness",
    description: "من يشهد بالحقيقة بدون تحيز",
    tags: ["يوسف", "شهادة", "عدل"],
    correctPhraseIds: ["شهد شاهد من اهلها"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "القريب",
    themeEnglish: "A Relative",
    description: "شخص من أقاربها أو أهلها",
    tags: ["يوسف", "قرابة", "عائلة"],
    correctPhraseIds: ["شاهد من اهلها"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "الكاد والهم",
    themeEnglish: "Almost Happened",
    description: "حالة الاقتراب من فعل شيء دون تحقيقه",
    tags: ["يوسف", "اقتراب", "كاد"],
    correctPhraseIds: ["كادت تفعل ذلك"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الدليل الواضح",
    themeEnglish: "Clear Evidence",
    description: "رؤية أو فهم دليل واضح لا لبس فيه",
    tags: ["يوسف", "دليل", "برهان"],
    correctPhraseIds: ["رأى برهان ربه"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "إحسان الضيافة",
    themeEnglish: "Excellent Hospitality",
    description: "معاملة الضيف بإحسان وإكرام",
    tags: ["يوسف", "ضيافة", "إكرام"],
    correctPhraseIds: ["احسن مثوى"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "داخل البيت",
    themeEnglish: "Inside the House",
    description: "المكان الداخلي من البيت",
    tags: ["يوسف", "مكان", "بيت"],
    correctPhraseIds: ["في بيتها"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "عند الباب",
    themeEnglish: "At the Door",
    description: "حالة الوقوف عند مدخل البيت",
    tags: ["يوسف", "موضع", "باب"],
    correctPhraseIds: ["وقفوا على الباب"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "الحيلة والتخطيط",
    themeEnglish: "Scheme and Planning",
    description: "كلمة تعني خطة أو حيلة خفية",
    tags: ["يوسف", "خطة", "مكر"],
    correctPhraseIds: ["كيدا"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الطفل الصغير",
    themeEnglish: "Small Child",
    description: "كلمة قرآنية لطفل صغير جداً",
    tags: ["يوسف", "طفل", "رضيع"],
    correctPhraseIds: ["صبيا"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "عصر الثمار",
    themeEnglish: "Pressing Fruits",
    description: "فعل قرآني عن استخراج عصير الثمار",
    tags: ["يوسف", "ثمار", "عصر"],
    correctPhraseIds: ["تعصرون"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "السنابل",
    themeEnglish: "Grain Heads",
    description: "حبات القمح في سنابلها الخضراء",
    tags: ["يوسف", "نبات", "محصول"],
    correctPhraseIds: ["السنبل"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الخدم والمعاونون",
    themeEnglish: "Servants and Assistants",
    description: "كلمة تعني خادمين أو معاونين",
    tags: ["يوسف", "خدمة", "مساعدة"],
    correctPhraseIds: ["الغلمان"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الاختصاص",
    themeEnglish: "Exclusive Ownership",
    description: "جعل شيء خالصاً لشخص واحد فقط",
    tags: ["يوسف", "اختصاص", "خصوصية"],
    correctPhraseIds: ["لاتفتوهن احدا"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "القوة والأمانة",
    themeEnglish: "Strength and Trustworthiness",
    description: "تركيب قرآني عن إنسان قوي وأمين",
    tags: ["يوسف", "قوة", "أمانة"],
    correctPhraseIds: ["قال اجعلني على خزائن الارض اني حفيظ عليم"],
    difficulty: 3,
    category: "vocabulary",
  },
  {
    theme: "الحفاظ من الخطأ",
    themeEnglish: "Guarding Against Error",
    description: "الامتناع والتحفظ عن الوقوع في الخطأ",
    tags: ["يوسف", "حماية", "صيانة"],
    correctPhraseIds: ["حفيظ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الذكرى بعد النسيان",
    themeEnglish: "Remembrance After Forgetting",
    description: "فعل يعني تذكر شيء بعد نسيانه",
    tags: ["يوسف", "ذاكرة", "تذكر"],
    correctPhraseIds: ["ذكره بعد امة"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "دعاء يوسف",
    themeEnglish: "Joseph's Prayer",
    description: "الجملة القرآنية للدعاء بتوسيع الصدر",
    tags: ["يوسف", "دعاء", "توسيع"],
    correctPhraseIds: ["رب اشرح لي صدري ويسر لي امري"],
    difficulty: 3,
    category: "vocabulary",
  },
  {
    theme: "تأويل الرؤيا",
    themeEnglish: "Interpretation of Dreams",
    description: "تفسير الرؤى والأحلام",
    tags: ["يوسف", "رؤيا", "تفسير"],
    correctPhraseIds: ["تاويل الاحاديث"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الحقب والأزمان",
    themeEnglish: "Long Periods",
    description: "كلمة قرآنية لمدة طويلة من الزمن",
    tags: ["يوسف", "زمن", "فترة"],
    correctPhraseIds: ["احقاب"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "المتاع المؤقت",
    themeEnglish: "Temporary Enjoyment",
    description: "متاع يستفاد منه لكن لفترة محدودة",
    tags: ["يوسف", "متاع", "زوال"],
    correctPhraseIds: ["متاع الحياة الدنيا"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ظلمات البئر",
    themeEnglish: "Darkness of the Well",
    description: "الظلمة العميقة داخل البئر",
    tags: ["يوسف", "ظلمة", "بئر"],
    correctPhraseIds: ["في ظلمات الجب"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الشيطان يزين",
    themeEnglish: "Satan Beautifies",
    description: "جملة قرآنية عن تجميل الشيطان للذنب",
    tags: ["يوسف", "شيطان", "تجميل"],
    correctPhraseIds: ["زين لهم سوء اعمالهم"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الأب والعم",
    themeEnglish: "Father and Uncle",
    description: "كلمة أصلها من العقب وأطلقت على الأب",
    tags: ["يوسف", "أب", "نسب"],
    correctPhraseIds: ["أب"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "مصدر الحزن",
    themeEnglish: "Source of Sorrow",
    description: "كلمة تعني مصدر الحزن الشديد",
    tags: ["يوسف", "حزن", "أسف"],
    correctPhraseIds: ["حزن"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "البيضاء من الله",
    themeEnglish: "Whitened by Allah",
    description: "يد بيضاء من غير مرض أو سوء",
    tags: ["يوسف", "معجزة", "بياض"],
    correctPhraseIds: ["تخرج يدك بيضاء من غير سوء"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الدم الكاذب",
    themeEnglish: "False Blood",
    description: "دم مزيف موضوع على القميص",
    tags: ["يوسف", "خديعة", "دم"],
    correctPhraseIds: ["دم كذب على قميصه"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الأرض القفرة",
    themeEnglish: "Barren Land",
    description: "الصحراء الواسعة الخالية",
    tags: ["يوسف", "صحراء", "خلاء"],
    correctPhraseIds: ["ارض"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "فتش الرحال",
    themeEnglish: "Search the Luggage",
    description: "فعل يعني البحث والفتش في الأمتعة",
    tags: ["يوسف", "بحث", "فتش"],
    correctPhraseIds: ["ختلناها"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "البضاعة الرخيصة",
    themeEnglish: "Cheap Goods",
    description: "بضاعة قليلة القيمة جداً",
    tags: ["يوسف", "تجارة", "رخص"],
    correctPhraseIds: ["بضاعة مجحفة"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "نداء المنادي",
    themeEnglish: "Cry of the Crier",
    description: "نداء أو صيحة من منادٍ بأمر معين",
    tags: ["يوسف", "صوت", "نداء"],
    correctPhraseIds: ["يا ايها العير"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "العير والقافلة",
    themeEnglish: "Caravan and Goods",
    description: "كلمة تعني القافلة أو الإبل المحملة",
    tags: ["يوسف", "نقل", "تجارة"],
    correctPhraseIds: ["عير"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الصواع",
    themeEnglish: "The Cup",
    description: "الكأس أو الإناء الذي يشرب به الملك",
    tags: ["يوسف", "آنية", "شراب"],
    correctPhraseIds: ["صواع"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "حصة البعير",
    themeEnglish: "Camel's Share",
    description: "نيل حصة إضافية كحصة بعير زائد",
    tags: ["يوسف", "حصة", "زيادة"],
    correctPhraseIds: ["قال اجعل لي بها"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "قسم بالله",
    themeEnglish: "Swearing by Allah",
    description: "فعل يعني القسم والحلف بالله",
    tags: ["يوسف", "حلف", "قسم"],
    correctPhraseIds: ["تالله"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الشدة على الظالمين",
    themeEnglish: "Harshness on the Oppressive",
    description: "الأمر بمنع الظلم وتشديد العقوبة",
    tags: ["يوسف", "عدالة", "شدة"],
    correctPhraseIds: ["لا تظلموا"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "البحث والتتبع",
    themeEnglish: "Searching and Tracking",
    description: "فعل يعني البحث والتتبع عن الأخبار",
    tags: ["يوسف", "بحث", "تتبع"],
    correctPhraseIds: ["اقصص الخبر"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الصبر بلا شكوى",
    themeEnglish: "Patience Without Complaint",
    description: "الصبر الذي لا يصاحبه شكوى أو تذمر",
    tags: ["يوسف", "صبر", "تسليم"],
    correctPhraseIds: ["فصبر جميل"],
    difficulty: 2,
    category: "vocabulary",
  },

  // Group 2: General Quranic Structures (Questions 41-70)
  {
    theme: "الاستماع بخشوع",
    themeEnglish: "Listening Intently",
    description: "الاستماع بإصغاء شديد وخضوع",
    tags: ["استماع", "خشوع", "انتباه"],
    correctPhraseIds: ["استمعوا"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "الكبرياء والتكبر",
    themeEnglish: "Pride and Arrogance",
    description: "الابتعاد عن الحق بنفس متكبرة",
    tags: ["كبر", "عجب", "تكبر"],
    correctPhraseIds: ["استكبرتم"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الخوف الشديد",
    themeEnglish: "Great Fear",
    description: "خوف شديد يسيطر على الإنسان",
    tags: ["خوف", "رهبة", "فزع"],
    correctPhraseIds: ["خوفا"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "الغرور والكبر",
    themeEnglish: "Conceit and Vanity",
    description: "كبر النفس والغرور بالنفس",
    tags: ["غرور", "كبر", "عجب"],
    correctPhraseIds: ["استكبارا"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الكلام الباطل",
    themeEnglish: "Vain Talk",
    description: "كلام باطل يلهي عن الحق",
    tags: ["لغو", "هراء", "باطل"],
    correctPhraseIds: ["اللغو"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الاستقامة",
    themeEnglish: "Steadfastness",
    description: "فعل يعني الاستقامة والاعتدال",
    tags: ["استقامة", "عدل", "توازن"],
    correctPhraseIds: ["استقاموا"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "تجاوز الحد",
    themeEnglish: "Transgression",
    description: "تجاوز الحد والظلم",
    tags: ["ظلم", "تجاوز", "حد"],
    correctPhraseIds: ["طغوا"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "زيادة البركة",
    themeEnglish: "Increase in Blessing",
    description: "زيادة الخير والبركة",
    tags: ["بركة", "زيادة", "خير"],
    correctPhraseIds: ["زدناهم"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "الركوع والخشوع",
    themeEnglish: "Kneeling",
    description: "جاثياً على الركبتين في الخضوع",
    tags: ["ركوع", "خشوع", "سجود"],
    correctPhraseIds: ["ركع"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الاختبار",
    themeEnglish: "Trial",
    description: "كلمة أصلها الاختبار بالفتنة",
    tags: ["اختبار", "فتنة", "ابتلاء"],
    correctPhraseIds: ["بلاء"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الصبح والمساء",
    themeEnglish: "Morning and Evening",
    description: "كلمتان تعنيان أول النهار وآخره",
    tags: ["وقت", "صبح", "مساء"],
    correctPhraseIds: ["الغدو والآصال"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "البقايا المهدمة",
    themeEnglish: "Ruined Remains",
    description: "بقايا مهدمة من البيوت",
    tags: ["خراب", "بقايا", "دمار"],
    correctPhraseIds: ["الآثار"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الإعراض والترك",
    themeEnglish: "Turning Away",
    description: "فعل يعني اترك ولا تلتفت إليهم",
    tags: ["إعراض", "ترك", "تجاهل"],
    correctPhraseIds: ["اعرض"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الخوف في القلب",
    themeEnglish: "Fear in the Heart",
    description: "الإحساس بخوف أو قلق في القلب",
    tags: ["قلق", "خوف", "قلب"],
    correctPhraseIds: ["خاف"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الصياح والصرخة",
    themeEnglish: "Shouting",
    description: "رفع الصوت بصياح عالي",
    tags: ["صوت", "صرخة", "صياح"],
    correctPhraseIds: ["صرخ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "التوبة والرجوع",
    themeEnglish: "Repentance",
    description: "الرجوع إلى الله بتوبة نصوح",
    tags: ["توبة", "رجوع", "ندم"],
    correctPhraseIds: ["تاب"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الوفاء بالعهد",
    themeEnglish: "Keeping Promise",
    description: "لم يخلف وعده أبداً",
    tags: ["عهد", "وعد", "وفاء"],
    correctPhraseIds: ["لم يخلف الميعاد"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الكلام المزخرف",
    themeEnglish: "Ornate Speech",
    description: "كلام مزخرف يضلل الناس",
    tags: ["كلام", "فتنة", "ضلال"],
    correctPhraseIds: ["قول غرور"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ضياء الشمس",
    themeEnglish: "Sunlight",
    description: "كلمتان تصفان ضياء الشمس القوي",
    tags: ["ضوء", "شمس", "إضاءة"],
    correctPhraseIds: ["ضياء"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "المنع والصد",
    themeEnglish: "Preventing",
    description: "فعل يعني يصد ويمنع عن الحق",
    tags: ["منع", "صد", "حجب"],
    correctPhraseIds: ["صد"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الخوف والرهبة",
    themeEnglish: "Fear and Awe",
    description: "خوف ورهبة من الله",
    tags: ["خشية", "خوف", "رهبة"],
    correctPhraseIds: ["خشية"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "العذاب والعقاب",
    themeEnglish: "Torment and Punishment",
    description: "عذاب أو عقوبة من الله",
    tags: ["عذاب", "عقاب", "بلاء"],
    correctPhraseIds: ["عذاب"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "الشراب السهل",
    themeEnglish: "Easy Drink",
    description: "شراب سهل الهضم",
    tags: ["شراب", "سهولة", "ماء"],
    correctPhraseIds: ["رقيق"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الكلام الخافت",
    themeEnglish: "Whisper",
    description: "يتحدثون بصوت خافت منخفض",
    tags: ["صوت", "خفوت", "همس"],
    correctPhraseIds: ["يتناجون"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "المقادير الصغيرة",
    themeEnglish: "Insignificant Amounts",
    description: "مقادير صغيرة جداً لا قيمة لها",
    tags: ["قلة", "تفاهة", "ضآلة"],
    correctPhraseIds: ["ذرة", "مثقال", "قطمير"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "عدم التذوق",
    themeEnglish: "Not Tasting",
    description: "لم يذوقوا طعمه بعد",
    tags: ["طعم", "تجربة", "عدم"],
    correctPhraseIds: ["ذاق"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الإيثار",
    themeEnglish: "Preference",
    description: "يقدم غيره على نفسه",
    tags: ["عطاء", "تضحية", "إيثار"],
    correctPhraseIds: ["آثر"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الافتتان بالجمال",
    themeEnglish: "Bewitched by Beauty",
    description: "افتتن بجمالها",
    tags: ["جمال", "افتتان", "تعلق"],
    correctPhraseIds: ["الهاه"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "غض البصر",
    themeEnglish: "Lowering the Gaze",
    description: "يحفظ بصره ولا ينظر إلا إلى ما يليق",
    tags: ["طهارة", "عفة", "حياء"],
    correctPhraseIds: ["غض البصر"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الضيق والحصر",
    themeEnglish: "Constriction",
    description: "مضيقاً عليه أو محصوراً",
    tags: ["ضيق", "حصار", "ازدحام"],
    correctPhraseIds: ["ضاق"],
    difficulty: 2,
    category: "vocabulary",
  },

  // Group 3: Conversational Phrases (Questions 71-100)
  {
    theme: "السؤال عن الأخبار",
    themeEnglish: "Asking About News",
    description: "ما شأنك؟ ما خبرك؟ كيف أنت؟",
    tags: ["سؤال", "تحية", "أخبار"],
    correctPhraseIds: ["ما شأنك"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "التأكيد والتحقيق",
    themeEnglish: "Affirmation",
    description: "كلمة تعني حقاً وحقيقةً",
    tags: ["تأكيد", "يقين", "فعلا"],
    correctPhraseIds: ["قد"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "الاستماع التام",
    themeEnglish: "Full Attention",
    description: "أصغى إليّ السمع والبصر",
    tags: ["استماع", "انتباه", "تركيز"],
    correctPhraseIds: ["اصغت"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "السؤال عن المصدر",
    themeEnglish: "Asking About Source",
    description: "من أين جاءك هذا؟",
    tags: ["سؤال", "مصدر", "أصل"],
    correctPhraseIds: ["من اين"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "الهم والنية",
    themeEnglish: "Intention",
    description: "همّ بأن يفعل شيئاً",
    tags: ["نية", "قصد", "عزم"],
    correctPhraseIds: ["همّ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "آهات الندم",
    themeEnglish: "Sighs of Regret",
    description: "آهات ندم وألم",
    tags: ["ندم", "ألم", "حزن"],
    correctPhraseIds: ["يا ويلتا"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الاستسلام لله",
    themeEnglish: "Submission to Allah",
    description: "مطيعاً خاضعاً لله",
    tags: ["طاعة", "خضوع", "إسلام"],
    correctPhraseIds: ["اسلم"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "بذل الجهد",
    themeEnglish: "Striving",
    description: "يجتهد ويبذل جهداً",
    tags: ["جهد", "عمل", "سعي"],
    correctPhraseIds: ["سعى"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الجدال والخصومة",
    themeEnglish: "Argument",
    description: "يتجادلون ويتخاصمون",
    tags: ["جدل", "خصام", "نزاع"],
    correctPhraseIds: ["تجادلون"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "توسيع الرزق",
    themeEnglish: "Expanding Sustenance",
    description: "يوسّع الرزق لمن يشاء",
    tags: ["رزق", "توسيع", "عطاء"],
    correctPhraseIds: ["يبسط الرزق"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الأمل والرغبة",
    themeEnglish: "Hope",
    description: "أمل ورغبة قوية",
    tags: ["أمل", "طمع", "رجاء"],
    correctPhraseIds: ["طمع"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الإعراض والابتعاد",
    themeEnglish: "Turning Away",
    description: "أعرض وابتعد عن الطريق",
    tags: ["إعراض", "ابتعاد", "ترك"],
    correctPhraseIds: ["ولى"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الانحراف عن الحق",
    themeEnglish: "Deviation",
    description: "يميل عن الحق",
    tags: ["انحراف", "ظلم", "ضلال"],
    correctPhraseIds: ["زاغ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "حمل الأعباء",
    themeEnglish: "Bearing Burdens",
    description: "يحملون أعباءكم",
    tags: ["حمل", "عبء", "مسؤولية"],
    correctPhraseIds: ["تحمل"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "المطر الشديد",
    themeEnglish: "Heavy Rain",
    description: "مطر شديد ينزل فجأة",
    tags: ["مطر", "ماء", "طوفان"],
    correctPhraseIds: ["غسق"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "التفكر والفهم",
    themeEnglish: "Reflection",
    description: "لتتفكروا وتفهموا",
    tags: ["فكر", "فهم", "تدبر"],
    correctPhraseIds: ["لعلكم تعقلون"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "القبح الشديد",
    themeEnglish: "Extreme Ugliness",
    description: "تشبيه لشيء قبيح المنظر جداً",
    tags: ["قبح", "شنعة", "تشويه"],
    correctPhraseIds: ["ساء مصرفا"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ضرب الأمثال",
    themeEnglish: "Setting Examples",
    description: "نقدم الأمثال لتوضيح الحق",
    tags: ["مثل", "توضيح", "شرح"],
    correctPhraseIds: ["نضرب الأمثال"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "السعي والجهد",
    themeEnglish: "Endeavor",
    description: "سعى لتحقيقها",
    tags: ["سعي", "محاولة", "جهد"],
    correctPhraseIds: ["جاهد"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "بسط اليد",
    themeEnglish: "Openhandedness",
    description: "يبسط يده بالعطاء",
    tags: ["عطاء", "كرم", "سخاء"],
    correctPhraseIds: ["يبسط"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الإحاطة بالعلم",
    themeEnglish: "All-Encompassing Knowledge",
    description: "محيط بكل شيء علماً",
    tags: ["علم", "إحاطة", "معرفة"],
    correctPhraseIds: ["بكل شيء عليم"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الخوض في الكلام",
    themeEnglish: "Wading in Talk",
    description: "يخوض في الكلام بلا فائدة",
    tags: ["كلام", "هراء", "لغو"],
    correctPhraseIds: ["يخوضون"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الصرف عن الحق",
    themeEnglish: "Diversion from Truth",
    description: "كيف يُصرفون عن الحق",
    tags: ["صرف", "عدول", "ابتعاد"],
    correctPhraseIds: ["صرفهم"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الفساد والبوار",
    themeEnglish: "Corruption and Ruin",
    description: "تفسد وتبور",
    tags: ["فساد", "هلاك", "دمار"],
    correctPhraseIds: ["بارت"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الإقامة الطويلة",
    themeEnglish: "Long Stay",
    description: "مكث مدة طويلة",
    tags: ["بقاء", "إقامة", "مدة"],
    correctPhraseIds: ["لبث"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "السقوط والوقوع",
    themeEnglish: "Falling",
    description: "سقطت ووقعت",
    tags: ["سقوط", "وقوع", "خسارة"],
    correctPhraseIds: ["خرّ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "نسيان الشيطان",
    themeEnglish: "Satan's Forgetfulness",
    description: "أنساه الشيطان",
    tags: ["نسيان", "شيطان", "غفلة"],
    correctPhraseIds: ["نسيه الشيطان"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الحلف والقسم",
    themeEnglish: "Swearing an Oath",
    description: "حلف وأقسم",
    tags: ["حلف", "قسم", "عهد"],
    correctPhraseIds: ["أقسم"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الوقوع في الإثم",
    themeEnglish: "Committing Sin",
    description: "وقع في الإثم والذنب",
    tags: ["إثم", "ذنب", "معصية"],
    correctPhraseIds: ["وقع"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "الانفصال والترك",
    themeEnglish: "Separation",
    description: "انفصل وترك الشيء",
    tags: ["انفصال", "ترك", "عزل"],
    correctPhraseIds: ["انفصل"],
    difficulty: 2,
    category: "vocabulary",
  },
];

async function seedVocabularyQuestions() {
  try {
    console.log("🌱 Seeding 100 Quranic vocabulary questions...");
    
    for (const question of vocabularyQuestions) {
      const existingQuestion = await db.query.questionBanks.findFirst({
        where: (qb) => qb.theme === question.theme
      });

      if (!existingQuestion) {
        await db.insert(questionBanks).values(question);
        console.log(`✓ Added: ${question.themeEnglish}`);
      }
    }

    console.log("✅ Successfully seeded 100 vocabulary questions!");
  } catch (error) {
    console.error("❌ Error seeding questions:", error);
    throw error;
  }
}

seedVocabularyQuestions();
