import { db } from "./db";
import { questionBanks } from "@shared/schema";

// 100 Commerce/Trade vocabulary questions with Quranic word answers
// All answers are actual Quranic words used in their linguistic (not religious) meaning
const commerceQuestions = [
  // Group 1-20: مفاهيم أساسية في البيع والشراء
  {
    theme: "ما الكلمة التي نستخدمها لوصف الأشياء التي يعرضها التاجر للبيع في متجره؟",
    themeEnglish: "What word describes items a merchant displays for sale in their store?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "بضاعة", "سلع"],
    correctPhraseIds: ["بِضَاعَة"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على عملية إعطاء شيء وأخذ ثمنه في المقابل؟",
    themeEnglish: "What is the name for the process of giving something and receiving payment in return?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "بيع", "معاملة"],
    correctPhraseIds: ["البَيْع"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن دفع المال للحصول على شيء نحتاجه؟",
    themeEnglish: "What word expresses paying money to obtain something we need?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "شراء", "اقتناء"],
    correctPhraseIds: ["اشْتَرَوْا"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يطلق على المال الذي يدفعه المشتري مقابل السلعة؟",
    themeEnglish: "What is the name for money paid by a buyer for goods?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "ثمن", "قيمة"],
    correctPhraseIds: ["ثَمَن"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تصف الزيادة التي يحصل عليها التاجر فوق كلفة البضاعة؟",
    themeEnglish: "What word describes the increase a merchant receives above the cost of goods?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "ربح", "كسب"],
    correctPhraseIds: ["رَبِحَت"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي نطلقه على النقص الذي يتعرض له التاجر عندما لا يغطي ثمن البيع تكلفة البضاعة؟",
    themeEnglish: "What is the name for the loss when sale price doesn't cover cost?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "خسارة", "نقص"],
    correctPhraseIds: ["خَسِرُوا"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبّر عن الاتفاق المكتوب بين طرفين على بيع شيء أو تقديم خدمة؟",
    themeEnglish: "What word describes a written agreement between two parties for sale or service?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "عقد", "اتفاق"],
    correctPhraseIds: ["عَقْد"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على المال الذي يُعطى لشخص ليعمل به في التجارة ويعيده لاحقًا؟",
    themeEnglish: "What is the name for money given to someone to trade with and return later?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "قرض", "دين"],
    correctPhraseIds: ["قَرْض"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تصف استرجاع البضاعة من المشتري إلى البائع بسبب عيب أو عدم رضا؟",
    themeEnglish: "What word describes returning goods from buyer to seller due to defect?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "رد", "إرجاع"],
    correctPhraseIds: ["رَدُّوهُ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي نطلقه على مجموعة السلع المختلفة التي يملكها التاجر في مخزنه؟",
    themeEnglish: "What is the name for the collection of goods a merchant has in storage?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "متاع", "سلع"],
    correctPhraseIds: ["مَتَاع"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي نستخدمها لوصف ارتفاع أسعار السلع في السوق؟",
    themeEnglish: "What word describes rising prices of goods in the market?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "زيادة", "غلاء"],
    correctPhraseIds: ["زَادَ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على انخفاض أسعار السلع في السوق؟",
    themeEnglish: "What is the name for falling prices of goods in the market?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "نقص", "رخص"],
    correctPhraseIds: ["نَقَصَ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن تبادل سلعة بسلعة من غير استخدام النقود؟",
    themeEnglish: "What word describes exchanging goods for goods without money?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "مقايضة", "تبادل"],
    correctPhraseIds: ["بَدَّلْنَا"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي نطلقه على المال المعدني أو الورقي الذي يتعامل به الناس في الشراء والبيع؟",
    themeEnglish: "What is the name for metal or paper money used in buying and selling?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "دراهم", "نقود"],
    correctPhraseIds: ["دَرَاهِم"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تدل على دفع جزء من الثمن الآن والباقي في وقت لاحق؟",
    themeEnglish: "What word indicates paying part now and the rest later?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "أجل", "تقسيط"],
    correctPhraseIds: ["أَجَل"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يعبر عن تحديد الثمن بعد مساومة بين البائع والمشتري؟",
    themeEnglish: "What is the name for setting a price after negotiation between buyer and seller?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "اتفاق", "صفقة"],
    correctPhraseIds: ["تَرَاضٍ"],
    difficulty: 3,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تدل على مبلغ صغير يدفعه الزبون مقدّمًا لحجز السلعة؟",
    themeEnglish: "What word indicates a small amount paid in advance to reserve goods?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "عربون", "مقدم"],
    correctPhraseIds: ["سَلَف"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يطلق على السلع التي يشتريها التاجر من مكان بعيد ليبيعها في بلده؟",
    themeEnglish: "What is the name for goods a merchant buys from afar to sell locally?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "واردات", "استيراد"],
    correctPhraseIds: ["جَلَبُوا"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تصف بيع كمية كبيرة من البضائع لتجار صغار بدلاً من بيعها للمستهلك مباشرة؟",
    themeEnglish: "What word describes selling large quantities to small traders instead of consumers?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "جملة", "توزيع"],
    correctPhraseIds: ["كَثِير"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يعبر عن بيع السلعة مباشرة للمستهلك النهائي في المحل؟",
    themeEnglish: "What is the name for selling directly to the final consumer in a shop?",
    description: "مفاهيم أساسية في البيع والشراء",
    tags: ["تجارة", "تجزئة", "مفرق"],
    correctPhraseIds: ["قَلِيل"],
    difficulty: 2,
    category: "vocabulary",
  },

  // Group 21-40: الأسواق، النقل، الحركة التجارية
  {
    theme: "ما الكلمة التي نستخدمها لوصف المكان الذي تجتمع فيه المحلات لبيع مختلف السلع للناس؟",
    themeEnglish: "What word describes where shops gather to sell various goods?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["سوق", "تجارة", "محلات"],
    correctPhraseIds: ["الأَسْوَاق"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على مجموعة من المحلات المتجاورة التي تبيع أنواعًا متقاربة من البضائع؟",
    themeEnglish: "What is the name for adjacent shops selling similar goods?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["سوق", "صف", "متاجر"],
    correctPhraseIds: ["صَفّ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن الرحلة التجارية التي يقطع فيها التجار مسافات طويلة لنقل بضائعهم؟",
    themeEnglish: "What word describes a trade journey where merchants travel long distances?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["تجارة", "رحلة", "سفر"],
    correctPhraseIds: ["رِحْلَة"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يطلق على وسيلة نقل كبيرة تحمل البضائع عبر البحر؟",
    themeEnglish: "What is the name for a large transport that carries goods across the sea?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["نقل", "سفينة", "بحر"],
    correctPhraseIds: ["الفُلْك"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تصف وسيلة نقل تحمل البضاعة من مدينة إلى مدينة عبر البر؟",
    themeEnglish: "What word describes transport carrying goods from city to city over land?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["نقل", "قافلة", "بر"],
    correctPhraseIds: ["العِير"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على المكان الذي تُخزَّن فيه البضاعة قبل توزيعها على المحلات؟",
    themeEnglish: "What is the name for where goods are stored before distribution?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["تخزين", "مستودع", "خزن"],
    correctPhraseIds: ["خَزَائِن"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي نستخدمها لوصف انتقال السلع من بلد إلى بلد لأجل البيع؟",
    themeEnglish: "What word describes goods moving from country to country for sale?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["تجارة", "نقل", "تصدير"],
    correctPhraseIds: ["تِجَارَة"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على إدخال البضائع من الخارج إلى داخل البلد؟",
    themeEnglish: "What is the name for bringing goods from outside into the country?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["استيراد", "إدخال", "جلب"],
    correctPhraseIds: ["أَدْخِلُوا"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن إخراج البضائع من البلد لبيعها في بلدان أخرى؟",
    themeEnglish: "What word describes exporting goods from the country to sell elsewhere?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["تصدير", "إخراج", "بيع"],
    correctPhraseIds: ["أَخْرَجَ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يطلق على الطريق الذي تسلكه البضائع من المصنع حتى تصل إلى يد المشتري؟",
    themeEnglish: "What is the name for the path goods take from factory to buyer?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["طريق", "مسار", "توزيع"],
    correctPhraseIds: ["سَبِيل"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تدل على المدينة أو المنطقة التي تشتهر بتصدير نوع معين من السلع؟",
    themeEnglish: "What word indicates a city or region famous for exporting certain goods?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["مصدر", "منشأ", "بلد"],
    correctPhraseIds: ["بَلَد"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي نستخدمه لوصف الحركة النشيطة للناس في الأسواق بيعًا وشراءً؟",
    themeEnglish: "What is the name for active movement of people buying and selling in markets?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["نشاط", "حركة", "سوق"],
    correctPhraseIds: ["يَمْشُون"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن المكان الذي تُوزع منه البضائع على المحلات الصغيرة؟",
    themeEnglish: "What word describes where goods are distributed to small shops?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["توزيع", "مركز", "مستودع"],
    correctPhraseIds: ["مَقْسُوم"],
    difficulty: 3,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يطلق على مجموعة تجار يتعاونون على استيراد بضائع معينة وتوزيعها؟",
    themeEnglish: "What is the name for merchants cooperating to import and distribute goods?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["شراكة", "تعاون", "تجار"],
    correctPhraseIds: ["شُرَكَاء"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تصف انتظار البضاعة لفترة طويلة في الميناء أو المستودع قبل توزيعها؟",
    themeEnglish: "What word describes goods waiting long in port or warehouse before distribution?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["انتظار", "تأخير", "ركود"],
    correctPhraseIds: ["لَبِثَ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على تكلفة نقل البضاعة من مكان لآخر؟",
    themeEnglish: "What is the name for the cost of transporting goods from place to place?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["أجرة", "نقل", "تكلفة"],
    correctPhraseIds: ["أَجْر"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي نستخدمها لوصف تلف جزء من البضاعة أثناء النقل؟",
    themeEnglish: "What word describes damage to goods during transport?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["تلف", "ضرر", "خسارة"],
    correctPhraseIds: ["فَسَدَ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يطلق على الأوراق التي ترافق شحنة البضاعة وتوضح محتواها وكمياتها؟",
    themeEnglish: "What is the name for papers accompanying a shipment showing contents?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["وثائق", "أوراق", "سجل"],
    correctPhraseIds: ["كِتَاب"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن إيقاف شحنة تجارية مؤقتًا عند الحدود للفحص أو الإجراءات؟",
    themeEnglish: "What word describes temporarily stopping a shipment at borders for inspection?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["حجز", "إيقاف", "فحص"],
    correctPhraseIds: ["حَبْس"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي نستخدمه لوصف المكان الذي تُعرض فيه البضاعة بشكل منظم لجذب المشترين؟",
    themeEnglish: "What is the name for where goods are displayed attractively for buyers?",
    description: "الأسواق والنقل والحركة التجارية",
    tags: ["عرض", "متجر", "واجهة"],
    correctPhraseIds: ["زِينَة"],
    difficulty: 2,
    category: "vocabulary",
  },

  // Group 41-60: الأشخاص والعلاقات التجارية
  {
    theme: "ما الكلمة التي نستخدمها لوصف الشخص الذي يشتري السلع بهدف بيعها بربح؟",
    themeEnglish: "What word describes someone who buys goods to sell for profit?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["تاجر", "بائع", "ربح"],
    correctPhraseIds: ["تَاجِر"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يطلق على الشخص الذي يدخل المتجر باحثًا عن شيء يشتريه؟",
    themeEnglish: "What is the name for someone entering a store looking to buy?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["زبون", "مشتري", "عميل"],
    correctPhraseIds: ["سَائِل"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن الشخص الذي يقف بين البائع والمشتري ويقرّب الصفقة بينهما؟",
    themeEnglish: "What word describes someone who mediates between buyer and seller?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["وسيط", "سمسار", "دلال"],
    correctPhraseIds: ["وَسِيط"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي نطلقه على الشخص الذي يعمل بأجر عند التاجر في المحل؟",
    themeEnglish: "What is the name for someone working for wages at a merchant's shop?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["عامل", "أجير", "موظف"],
    correctPhraseIds: ["أَجِير"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تصف الشخص الذي يتولى الإشراف على مجموعة من العمال في مؤسسة تجارية؟",
    themeEnglish: "What word describes someone supervising workers in a business?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["مشرف", "رئيس", "مدير"],
    correctPhraseIds: ["قَائِم"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على الشخص الذي يملك المال ويعطيه لتاجر آخر ليتاجر به؟",
    themeEnglish: "What is the name for someone who gives money to a merchant to trade with?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["مستثمر", "ممول", "صاحب مال"],
    correctPhraseIds: ["صَاحِب"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن الشخص الذي يدير متجرًا أو مؤسسة نيابة عن المالك؟",
    themeEnglish: "What word describes someone managing a shop on behalf of the owner?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["وكيل", "مدير", "نائب"],
    correctPhraseIds: ["وَكِيل"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي نستخدمه لوصف الشخص الذي يقدّم خدمات نقل البضاعة مقابل أجر؟",
    themeEnglish: "What is the name for someone providing goods transport services for pay?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["ناقل", "حمال", "سائق"],
    correctPhraseIds: ["حَامِل"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تصف الشخص الذي يعرض بضاعة غيره للبيع مقابل نسبة من الثمن؟",
    themeEnglish: "What word describes someone selling others' goods for a commission?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["سمسار", "وسيط", "عمولة"],
    correctPhraseIds: ["شَهِيد"],
    difficulty: 3,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يطلق على الشخص الذي يشتري سلعة ثم يبيعها من جديد بسعر أعلى في نفس اليوم؟",
    themeEnglish: "What is the name for someone buying and reselling goods same day at higher price?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["مضارب", "تجارة", "ربح سريع"],
    correctPhraseIds: ["مُشْتَرِي"],
    difficulty: 3,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي نستخدمها لوصف شخصين أو أكثر يشتركون في رأس مال واحد لعمل تجاري؟",
    themeEnglish: "What word describes two or more sharing capital for a business?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["شركاء", "مشاركة", "رأس مال"],
    correctPhraseIds: ["شُرَكَاء"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على الشخص الذي يتأخر في سداد ما عليه من ثمن للبائع؟",
    themeEnglish: "What is the name for someone delaying payment to a seller?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["مدين", "متأخر", "دين"],
    correctPhraseIds: ["غَارِم"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن الشخص الذي يراجع حسابات التاجر ويتأكد من صحتها؟",
    themeEnglish: "What word describes someone reviewing and verifying a merchant's accounts?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["محاسب", "مراجع", "حساب"],
    correctPhraseIds: ["حَسِيب"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي نطلقه على الشخص الذي يصنّف البضاعة ويجهزها للعرض في المتجر؟",
    themeEnglish: "What is the name for someone categorizing and preparing goods for display?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["مرتب", "منظم", "عامل"],
    correctPhraseIds: ["مُرَتِّب"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تصف الشخص الذي يتولى التفاوض على الأسعار باسم مؤسسة كبيرة؟",
    themeEnglish: "What word describes someone negotiating prices for a large organization?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["مفاوض", "ممثل", "مندوب"],
    correctPhraseIds: ["رَسُول"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي نستخدمه لوصف مجموعة من التجار يتعاونون فيما بينهم لمنافسة غيرهم؟",
    themeEnglish: "What is the name for merchants cooperating to compete with others?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["تحالف", "تعاون", "منافسة"],
    correctPhraseIds: ["جَمِيع"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن مجموعة الشركات التي تعمل في نفس المجال وتتنافس على الزبائن؟",
    themeEnglish: "What word describes companies working in the same field competing for customers?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["منافسون", "سوق", "تنافس"],
    correctPhraseIds: ["مُتَنَافِسُون"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على الشخص الذي يأتي إلى السوق ليبحث عن عروض بأقل الأسعار؟",
    themeEnglish: "What is the name for someone coming to market looking for lowest prices?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["باحث", "متسوق", "موفر"],
    correctPhraseIds: ["طَالِب"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي نستخدمها لوصف الشخص الذي يتنقل بين البيوت لبيع بضاعته مباشرة للناس؟",
    themeEnglish: "What word describes someone traveling between homes to sell goods directly?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["بائع متجول", "جوال", "متنقل"],
    correctPhraseIds: ["سَائِر"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يعبر عن الشخص الذي يختار البضائع ويقرر كمياتها وأنواعها في المتجر؟",
    themeEnglish: "What is the name for someone selecting goods and deciding quantities in a shop?",
    description: "الأشخاص والعلاقات التجارية",
    tags: ["مشتري", "منتقي", "مختار"],
    correctPhraseIds: ["مُخْتَار"],
    difficulty: 2,
    category: "vocabulary",
  },

  // Group 61-80: القياس، الحساب، التنظيم
  {
    theme: "ما الكلمة التي نستخدمها لوصف عملية وزن السلع لمعرفة كميتها بالميزان؟",
    themeEnglish: "What word describes weighing goods to determine quantity with scales?",
    description: "القياس والحساب والتنظيم",
    tags: ["وزن", "كمية", "ميزان"],
    correctPhraseIds: ["وَزْن"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على قياس حجم السائل في أوعية مخصصة لذلك؟",
    themeEnglish: "What is the name for measuring liquid volume in designated containers?",
    description: "القياس والحساب والتنظيم",
    tags: ["كيل", "قياس", "سائل"],
    correctPhraseIds: ["كَيْل"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن الأداة التي توزن بها البضائع في المتجر أو المستودع؟",
    themeEnglish: "What word describes the tool used to weigh goods in shop or warehouse?",
    description: "القياس والحساب والتنظيم",
    tags: ["ميزان", "أداة", "وزن"],
    correctPhraseIds: ["مِيزَان"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يطلق على وحدة الوزن التي تُستخدم في التجارة لقياس الكميات الكبيرة؟",
    themeEnglish: "What is the name for a weight unit used in trade for large quantities?",
    description: "القياس والحساب والتنظيم",
    tags: ["وحدة", "وزن", "قنطار"],
    correctPhraseIds: ["قِنطَار"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي نستخدمها لوصف عملية عدّ السلع قطعةً قطعة؟",
    themeEnglish: "What word describes counting goods piece by piece?",
    description: "القياس والحساب والتنظيم",
    tags: ["عد", "إحصاء", "حساب"],
    correctPhraseIds: ["عَدَد"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على دفتر تُسجَّل فيه عمليات البيع والشراء يوميًا؟",
    themeEnglish: "What is the name for a book recording daily buying and selling?",
    description: "القياس والحساب والتنظيم",
    tags: ["سجل", "دفتر", "كتاب"],
    correctPhraseIds: ["كِتَاب"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن تسجيل حركة الأموال الداخلة والخارجة من المتجر؟",
    themeEnglish: "What word describes recording money coming in and out of a shop?",
    description: "القياس والحساب والتنظيم",
    tags: ["حساب", "تسجيل", "مال"],
    correctPhraseIds: ["حِسَاب"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي نطلقه على عملية التأكد من أن كمية البضاعة في المخزن مطابقة لما هو مسجل في السجلات؟",
    themeEnglish: "What is the name for verifying stored goods match records?",
    description: "القياس والحساب والتنظيم",
    tags: ["جرد", "مطابقة", "تدقيق"],
    correctPhraseIds: ["أَحْصَى"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تصف تقسيم الأرباح بين الشركاء حسب نسبة متفق عليها؟",
    themeEnglish: "What word describes dividing profits among partners by agreed ratio?",
    description: "القياس والحساب والتنظيم",
    tags: ["قسمة", "توزيع", "نسبة"],
    correctPhraseIds: ["قِسْمَة"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على جمع الديون المستحقة على الزبائن وترتيبها في قوائم؟",
    themeEnglish: "What is the name for collecting and listing debts owed by customers?",
    description: "القياس والحساب والتنظيم",
    tags: ["ديون", "جمع", "ترتيب"],
    correctPhraseIds: ["دَيْن"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي نستخدمها لوصف مجموع ما يملكه التاجر من مال وبضاعة بعد خصم ما عليه من ديون؟",
    themeEnglish: "What word describes a merchant's total assets after subtracting debts?",
    description: "القياس والحساب والتنظيم",
    tags: ["رأس مال", "صافي", "ثروة"],
    correctPhraseIds: ["مَال"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يطلق على الزيادة المتوقعة في المبيعات خلال فترة قادمة؟",
    themeEnglish: "What is the name for expected increase in sales over a coming period?",
    description: "القياس والحساب والتنظيم",
    tags: ["نمو", "زيادة", "توقع"],
    correctPhraseIds: ["نَمَاء"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن خطة تنظيمية لتطوير المبيعات وزيادة عدد الزبائن؟",
    themeEnglish: "What word describes a plan to develop sales and increase customers?",
    description: "القياس والحساب والتنظيم",
    tags: ["خطة", "تطوير", "استراتيجية"],
    correctPhraseIds: ["تَدْبِير"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على عملية فحص البضاعة عند استلامها للتأكد من سلامتها وجودتها؟",
    themeEnglish: "What is the name for inspecting goods upon receipt to verify quality?",
    description: "القياس والحساب والتنظيم",
    tags: ["فحص", "تدقيق", "جودة"],
    correctPhraseIds: ["نَظَرَ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي نستخدمها لوصف وضع بطاقة صغيرة على السلعة توضح اسمها وسعرها؟",
    themeEnglish: "What word describes putting a small tag on goods showing name and price?",
    description: "القياس والحساب والتنظيم",
    tags: ["بطاقة", "سعر", "علامة"],
    correctPhraseIds: ["عَلامَة"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يطلق على تغليف السلعة بشكل يحميها ويجعلها جذابة للمشتري؟",
    themeEnglish: "What is the name for wrapping goods to protect and make them attractive?",
    description: "القياس والحساب والتنظيم",
    tags: ["تغليف", "حماية", "جمال"],
    correctPhraseIds: ["غِلاف"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن حساب التكلفة الحقيقية للسلعة من شراء ونقل وتخزين قبل تحديد سعر بيعها؟",
    themeEnglish: "What word describes calculating true cost of goods before setting sale price?",
    description: "القياس والحساب والتنظيم",
    tags: ["تكلفة", "حساب", "سعر"],
    correctPhraseIds: ["حَسَبَ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على تقسيم البضاعة إلى فئات حسب الجودة أو الحجم أو النوع؟",
    themeEnglish: "What is the name for dividing goods into categories by quality, size, or type?",
    description: "القياس والحساب والتنظيم",
    tags: ["تصنيف", "فئات", "ترتيب"],
    correctPhraseIds: ["صِنْف"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي نستخدمها لوصف عملية مراجعة الأسعار وتعديلها لتناسب ظروف السوق؟",
    themeEnglish: "What word describes reviewing and adjusting prices to match market conditions?",
    description: "القياس والحساب والتنظيم",
    tags: ["تعديل", "مراجعة", "سعر"],
    correctPhraseIds: ["بَدَّلَ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يطلق على عرض خاص يخفض فيه التاجر ثمن بعض السلع لفترة محدودة لجذب الزبائن؟",
    themeEnglish: "What is the name for a special offer where a merchant reduces prices temporarily?",
    description: "القياس والحساب والتنظيم",
    tags: ["عرض", "تخفيض", "خصم"],
    correctPhraseIds: ["تَخْفِيف"],
    difficulty: 2,
    category: "vocabulary",
  },

  // Group 81-100: المخاطر، الديون، التخطيط الطويل
  {
    theme: "ما الكلمة التي نستخدمها لوصف المال الذي يُستَحق على شخص بعد شراء بضاعة مؤجَّلة الثمن؟",
    themeEnglish: "What word describes money owed after buying goods on credit?",
    description: "المخاطر والديون والتخطيط",
    tags: ["دين", "مستحق", "أجل"],
    correctPhraseIds: ["دَيْن"],
    difficulty: 1,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على عدم قدرة التاجر على سداد ما عليه من ديون في مواعيدها؟",
    themeEnglish: "What is the name for a merchant's inability to pay debts on time?",
    description: "المخاطر والديون والتخطيط",
    tags: ["عجز", "إفلاس", "عسر"],
    correctPhraseIds: ["عُسْرَة"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن توقف متجر عن العمل بسبب خسائر متكررة وعدم تحقق الأرباح؟",
    themeEnglish: "What word describes a shop closing due to repeated losses?",
    description: "المخاطر والديون والتخطيط",
    tags: ["إغلاق", "خسارة", "توقف"],
    correctPhraseIds: ["بَوَار"],
    difficulty: 3,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي نطلقه على الخطر الذي يواجهه التاجر بسبب تقلب الأسعار في السوق؟",
    themeEnglish: "What is the name for risk a merchant faces due to market price fluctuations?",
    description: "المخاطر والديون والتخطيط",
    tags: ["خطر", "مخاطرة", "تقلب"],
    correctPhraseIds: ["خَطَر"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي نستخدمها لوصف تخزين كميات كبيرة من سلعة معيّنة على أمل بيعها بسعر أعلى لاحقًا؟",
    themeEnglish: "What word describes storing large quantities hoping to sell at higher price later?",
    description: "المخاطر والديون والتخطيط",
    tags: ["احتكار", "تخزين", "ادخار"],
    correctPhraseIds: ["ادَّخَرَ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على نقص شديد في سلعة مطلوبة في السوق؟",
    themeEnglish: "What is the name for severe shortage of a demanded product in the market?",
    description: "المخاطر والديون والتخطيط",
    tags: ["نقص", "ندرة", "قلة"],
    correctPhraseIds: ["قِلَّة"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن وفرة كبيرة في سلعة معيّنة بما يفوق حاجة المشترين؟",
    themeEnglish: "What word describes abundance of goods exceeding buyer needs?",
    description: "المخاطر والديون والتخطيط",
    tags: ["وفرة", "كثرة", "فائض"],
    correctPhraseIds: ["كَثْرَة"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي نطلقه على تحويل جزء من أرباح هذا العام إلى احتياطي للأعوام المقبلة؟",
    themeEnglish: "What is the name for converting part of this year's profits to reserves?",
    description: "المخاطر والديون والتخطيط",
    tags: ["احتياطي", "ادخار", "توفير"],
    correctPhraseIds: ["ذُخْر"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي نستخدمها لوصف وضع الأموال في مشروع تجاري جديد طمعًا في الربح المستقبلي؟",
    themeEnglish: "What word describes investing money in a new business hoping for future profit?",
    description: "المخاطر والديون والتخطيط",
    tags: ["استثمار", "مشروع", "ربح"],
    correctPhraseIds: ["أَنفَقَ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على خطة طويلة المدى لتوسيع نشاط الشركة ودخول أسواق جديدة؟",
    themeEnglish: "What is the name for a long-term plan to expand a company and enter new markets?",
    description: "المخاطر والديون والتخطيط",
    tags: ["خطة", "توسع", "استراتيجية"],
    correctPhraseIds: ["تَوَسُّع"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن انتقال التاجر من عمل صغير إلى نشاط أكبر بكثير في مدة قصيرة؟",
    themeEnglish: "What word describes a merchant moving from small work to much larger activity quickly?",
    description: "المخاطر والديون والتخطيط",
    tags: ["نمو", "توسع", "ازدهار"],
    correctPhraseIds: ["نَشَأَ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي نستخدمه لوصف مشاركة مؤسسة كبيرة لرأس مال وخبرة مؤسسة أصغر لتقوية تجارتها؟",
    themeEnglish: "What is the name for a large company sharing capital and expertise with a smaller one?",
    description: "المخاطر والديون والتخطيط",
    tags: ["شراكة", "دعم", "تعاون"],
    correctPhraseIds: ["شَارَكَ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تدل على بيع جزء من ملكية شركة مقابل الحصول على مال لتوسيع العمل؟",
    themeEnglish: "What word indicates selling part of company ownership for money to expand?",
    description: "المخاطر والديون والتخطيط",
    tags: ["حصة", "ملكية", "بيع"],
    correctPhraseIds: ["نَصِيب"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يطلق على شراء التاجر سلعًا من منطقة رخيصة وبيعها في منطقة أغلى؟",
    themeEnglish: "What is the name for buying goods from cheap area and selling in expensive area?",
    description: "المخاطر والديون والتخطيط",
    tags: ["تجارة", "نقل", "ربح"],
    correctPhraseIds: ["جَلَبَ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي نستخدمها لوصف اعتماد التاجر على مصدر واحد فقط لبضاعته مما يعرّضه للخطر عند توقفه؟",
    themeEnglish: "What word describes relying on one source for goods creating risk if it stops?",
    description: "المخاطر والديون والتخطيط",
    tags: ["اعتماد", "مصدر", "خطر"],
    correctPhraseIds: ["وَاحِد"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على توزيع مصادر البضاعة على أكثر من جهة لتقليل المخاطر؟",
    themeEnglish: "What is the name for distributing goods sources to reduce risk?",
    description: "المخاطر والديون والتخطيط",
    tags: ["توزيع", "تنويع", "مصادر"],
    correctPhraseIds: ["فَرَّقَ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تعبر عن الاتفاق على سعر ثابت لتوريد سلعة ما لمدة زمنية معينة رغم تغير ظروف السوق؟",
    themeEnglish: "What word describes agreeing on a fixed price for supply despite market changes?",
    description: "المخاطر والديون والتخطيط",
    tags: ["عقد", "ثابت", "التزام"],
    correctPhraseIds: ["عَهْد"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي نستخدمه لوصف دراسة مسبقة للسوق والزبائن قبل فتح مشروع تجاري جديد؟",
    themeEnglish: "What is the name for studying the market and customers before opening a new business?",
    description: "المخاطر والديون والتخطيط",
    tags: ["دراسة", "بحث", "تخطيط"],
    correctPhraseIds: ["عِلْم"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الكلمة التي تدل على تغيير نشاط المتجر من بيع سلعة إلى أخرى عندما تقل أرباح الأولى؟",
    themeEnglish: "What word indicates changing a shop's activity from one product to another when profits decline?",
    description: "المخاطر والديون والتخطيط",
    tags: ["تحويل", "تغيير", "انتقال"],
    correctPhraseIds: ["حَوَّلَ"],
    difficulty: 2,
    category: "vocabulary",
  },
  {
    theme: "ما الاسم الذي يدل على إيقاف عملية تجارية معينة بعد اكتشاف أنها لا تحقق أهداف الربح المطلوبة؟",
    themeEnglish: "What is the name for stopping a business operation after finding it doesn't meet profit goals?",
    description: "المخاطر والديون والتخطيط",
    tags: ["إيقاف", "توقف", "انسحاب"],
    correctPhraseIds: ["أَوْقَفَ"],
    difficulty: 2,
    category: "vocabulary",
  },
];

async function seedCommerceQuestions() {
  console.log("🏪 Starting to seed 100 commerce vocabulary questions...\n");
  
  let successCount = 0;
  let errorCount = 0;
  
  for (let i = 0; i < commerceQuestions.length; i++) {
    const q = commerceQuestions[i];
    try {
      await db.insert(questionBanks).values({
        theme: q.theme,
        themeEnglish: q.themeEnglish,
        description: q.description,
        tags: q.tags,
        correctPhraseIds: q.correctPhraseIds,
        difficulty: q.difficulty,
        category: q.category,
      });
      successCount++;
      console.log(`✅ [${i + 1}/100] Added: ${q.correctPhraseIds[0]}`);
    } catch (error: any) {
      errorCount++;
      console.error(`❌ [${i + 1}/100] Failed: ${q.theme.substring(0, 40)}... - ${error.message}`);
    }
  }
  
  console.log(`\n📊 Summary:`);
  console.log(`   ✅ Successfully added: ${successCount} questions`);
  console.log(`   ❌ Errors: ${errorCount}`);
  console.log(`\n🏪 Commerce vocabulary questions seeding complete!`);
}

seedCommerceQuestions()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("Fatal error:", error);
    process.exit(1);
  });
