import { db } from "./db";
import { questionBanks } from "@shared/schema";

// 80 Questions about the personality and character of a Da'iyah (caller to Islam)
// All answers are Quranic verses and expressions
const daiyahQuestions = [
  {
    theme: "ما الأساس الأول لشخصية الداعية إلى الله؟",
    themeEnglish: "What is the first foundation of a caller's personality?",
    description: "شخصية الداعية - الإخلاص",
    tags: ["داعية", "إخلاص", "عبادة"],
    correctPhraseIds: ["مُخْلِصِينَ لَهُ الدِّينَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يعرّف القرآن وظيفة الداعية؟",
    themeEnglish: "How does the Quran define the function of a caller?",
    description: "شخصية الداعية - الوظيفة",
    tags: ["داعية", "دعوة", "بصيرة"],
    correctPhraseIds: ["أَدْعُو إِلَى اللَّهِ عَلَى بَصِيرَةٍ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما شرط النجاح في الدعوة من جهة المنهج؟",
    themeEnglish: "What is the condition for success in calling from a methodological perspective?",
    description: "شخصية الداعية - البصيرة",
    tags: ["داعية", "منهج", "علم"],
    correctPhraseIds: ["عَلَى بَصِيرَةٍ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما الصفة الجامعة لخطاب الداعية للناس جميعًا؟",
    themeEnglish: "What is the comprehensive quality of a caller's address to all people?",
    description: "شخصية الداعية - الحكمة",
    tags: ["داعية", "حكمة", "موعظة"],
    correctPhraseIds: ["بِالْحِكْمَةِ وَالْمَوْعِظَةِ الْحَسَنَةِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يظهر رفق الداعية في كلامه؟",
    themeEnglish: "How does a caller's gentleness appear in speech?",
    description: "شخصية الداعية - الرفق",
    tags: ["داعية", "رفق", "لين"],
    correctPhraseIds: ["قَوْلًا لَيِّنًا"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "ما معيار التفوق في ميدان الدعوة في نظر القرآن؟",
    themeEnglish: "What is the standard of excellence in calling according to the Quran?",
    description: "شخصية الداعية - التفوق",
    tags: ["داعية", "دعوة", "فضل"],
    correctPhraseIds: ["وَمَنْ أَحْسَنُ قَوْلًا مِمَّنْ دَعَا إِلَى اللَّهِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يكون الداعية رحيمًا بالمدعوّين؟",
    themeEnglish: "How is a caller merciful to those being called?",
    description: "شخصية الداعية - الرحمة",
    tags: ["داعية", "رحمة", "رأفة"],
    correctPhraseIds: ["رَؤُوفٌ رَحِيمٌ"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "ما علاقة الدعوة بالصبر؟",
    themeEnglish: "What is the relationship between calling and patience?",
    description: "شخصية الداعية - الصبر",
    tags: ["داعية", "صبر", "ثبات"],
    correctPhraseIds: ["وَاصْبِرْ وَمَا صَبْرُكَ إِلَّا بِاللَّهِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يضبط الداعية غضبه عند الأذى؟",
    themeEnglish: "How does a caller control anger when harmed?",
    description: "شخصية الداعية - كظم الغيظ",
    tags: ["داعية", "غضب", "كظم"],
    correctPhraseIds: ["الْكَاظِمِينَ الْغَيْظَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما موقف الداعية من خصومه؟",
    themeEnglish: "What is a caller's stance toward opponents?",
    description: "شخصية الداعية - مواجهة الخصوم",
    tags: ["داعية", "خصوم", "إحسان"],
    correctPhraseIds: ["ادْفَعْ بِالَّتِي هِيَ أَحْسَنُ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يتعامل الداعية مع اختلاف الناس؟",
    themeEnglish: "How does a caller deal with people's differences?",
    description: "شخصية الداعية - الاختلاف",
    tags: ["داعية", "اختلاف", "تنوع"],
    correctPhraseIds: ["لَجَعَلَ النَّاسَ أُمَّةً وَاحِدَةً"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما مكانة الشورى في شخصية الداعية القائد؟",
    themeEnglish: "What is the place of consultation in a leader-caller's personality?",
    description: "شخصية الداعية - الشورى",
    tags: ["داعية", "شورى", "قيادة"],
    correctPhraseIds: ["وَأَمْرُهُمْ شُورَىٰ بَيْنَهُمْ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يكون الداعية متواضعًا؟",
    themeEnglish: "How is a caller humble?",
    description: "شخصية الداعية - التواضع",
    tags: ["داعية", "تواضع", "أخلاق"],
    correctPhraseIds: ["وَاقْصِدْ فِي مَشْيِكَ وَاغْضُضْ مِن صَوْتِكَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما مظهر الخشوع العملي في الداعية؟",
    themeEnglish: "What is the practical manifestation of humility in a caller?",
    description: "شخصية الداعية - الخشوع",
    tags: ["داعية", "خشوع", "صلاة"],
    correctPhraseIds: ["فِي صَلَاتِهِمْ خَاشِعُونَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "لماذا يجب على الداعية ضبط لسانه؟",
    themeEnglish: "Why must a caller control their tongue?",
    description: "شخصية الداعية - ضبط اللسان",
    tags: ["داعية", "لسان", "قول"],
    correctPhraseIds: ["قَوْلًا سَدِيدًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يحقّق الداعية الصدق مع الله ومع الناس؟",
    themeEnglish: "How does a caller achieve truthfulness with Allah and people?",
    description: "شخصية الداعية - الصدق",
    tags: ["داعية", "صدق", "تقوى"],
    correctPhraseIds: ["كُونُوا مَعَ الصَّادِقِينَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما السقف الأخلاقي الأعلى للداعية؟",
    themeEnglish: "What is the highest moral ceiling for a caller?",
    description: "شخصية الداعية - الخلق العظيم",
    tags: ["داعية", "خلق", "أخلاق"],
    correctPhraseIds: ["لَعَلَى خُلُقٍ عَظِيمٍ"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "كيف يوازن الداعية بين الشدة والرحمة؟",
    themeEnglish: "How does a caller balance firmness and mercy?",
    description: "شخصية الداعية - التوازن",
    tags: ["داعية", "شدة", "رحمة"],
    correctPhraseIds: ["أَشِدَّاءُ عَلَى الْكُفَّارِ رُحَمَاءُ بَيْنَهُمْ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما دور الخوف من الله في حماية الداعية من الانحراف؟",
    themeEnglish: "What role does fear of Allah play in protecting a caller from deviation?",
    description: "شخصية الداعية - الخشية",
    tags: ["داعية", "خشية", "خوف"],
    correctPhraseIds: ["فَلَا تَخْشَوُا النَّاسَ وَاخْشَوْنِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يضبط الداعية نيّته عند الشهرة ومدح الناس؟",
    themeEnglish: "How does a caller control intention when famous and praised?",
    description: "شخصية الداعية - النية",
    tags: ["داعية", "نية", "إخلاص"],
    correctPhraseIds: ["إِنَّمَا أَنَا بَشَرٌ مِثْلُكُمْ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما علاقة الدعوة بالعمل قبل القول؟",
    themeEnglish: "What is the relationship between calling and action before speech?",
    description: "شخصية الداعية - العمل",
    tags: ["داعية", "عمل", "قول"],
    correctPhraseIds: ["أَن تَقُولُوا مَا لَا تَفْعَلُونَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يربّي الداعية نفسه على الصدق العلمي؟",
    themeEnglish: "How does a caller train themselves on intellectual honesty?",
    description: "شخصية الداعية - الصدق العلمي",
    tags: ["داعية", "علم", "صدق"],
    correctPhraseIds: ["وَلَا تَقْفُ مَا لَيْسَ لَكَ بِهِ عِلْمٌ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "هل تكفي عاطفة الغيرة على الدين دون علم؟",
    themeEnglish: "Is emotional zeal for religion sufficient without knowledge?",
    description: "شخصية الداعية - العلم والعاطفة",
    tags: ["داعية", "علم", "غيرة"],
    correctPhraseIds: ["هَلْ يَسْتَوِي الَّذِينَ يَعْلَمُونَ وَالَّذِينَ لَا يَعْلَمُونَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يكون الداعية قدوةً في السلامة من الغيبة؟",
    themeEnglish: "How is a caller a role model in avoiding backbiting?",
    description: "شخصية الداعية - الغيبة",
    tags: ["داعية", "غيبة", "لسان"],
    correctPhraseIds: ["وَلَا يَغْتَب بَّعْضُكُم بَعْضًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما موقف الداعية من السخرية من المخالف؟",
    themeEnglish: "What is a caller's stance on mocking those who disagree?",
    description: "شخصية الداعية - السخرية",
    tags: ["داعية", "سخرية", "أدب"],
    correctPhraseIds: ["لَا يَسْخَرْ قَوْمٌ مِّن قَوْمٍ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يعبّر القرآن عن ضرورة الحلم في الداعية؟",
    themeEnglish: "How does the Quran express the necessity of forbearance in a caller?",
    description: "شخصية الداعية - الحلم",
    tags: ["داعية", "حلم", "سلام"],
    correctPhraseIds: ["قَالُوا سَلَامًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "هل على الداعية أن يتدرّج مع الناس؟",
    themeEnglish: "Should a caller be gradual with people?",
    description: "شخصية الداعية - التدرج",
    tags: ["داعية", "تدرج", "بيان"],
    correctPhraseIds: ["فَصَّلْنَاهُ عَلَى عِلْمٍ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما صفة التيسير في خطاب الداعية؟",
    themeEnglish: "What is the quality of ease in a caller's discourse?",
    description: "شخصية الداعية - التيسير",
    tags: ["داعية", "يسر", "رفق"],
    correctPhraseIds: ["يُرِيدُ اللَّهُ بِكُمُ الْيُسْرَ"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "كيف يوازن الداعية بين التبشير والإنذار؟",
    themeEnglish: "How does a caller balance good tidings and warning?",
    description: "شخصية الداعية - التبشير والإنذار",
    tags: ["داعية", "تبشير", "إنذار"],
    correctPhraseIds: ["مُبَشِّرًا وَنَذِيرًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما علاقة الدعوة بالرحمة العامة للعالمين؟",
    themeEnglish: "What is the relationship between calling and universal mercy?",
    description: "شخصية الداعية - الرحمة للعالمين",
    tags: ["داعية", "رحمة", "عالمين"],
    correctPhraseIds: ["رَحْمَةً لِّلْعَالَمِينَ"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "كيف يربّي الداعية نفسه على الصبر على طول الطريق؟",
    themeEnglish: "How does a caller train themselves on patience throughout the journey?",
    description: "شخصية الداعية - الصبر",
    tags: ["داعية", "صبر", "عزم"],
    correctPhraseIds: ["فَاصْبِرْ كَمَا صَبَرَ أُولُو الْعَزْمِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ماذا يصنع الداعية حين يرى قلة المستجيبين؟",
    themeEnglish: "What does a caller do when seeing few respondents?",
    description: "شخصية الداعية - قلة الاستجابة",
    tags: ["داعية", "استجابة", "صبر"],
    correctPhraseIds: ["بَاخِعٌ نَّفْسَكَ"],
    difficulty: 3,
    category: "thematic",
  },
  {
    theme: "ما موقع الاستغفار في حياة الداعية؟",
    themeEnglish: "What is the place of seeking forgiveness in a caller's life?",
    description: "شخصية الداعية - الاستغفار",
    tags: ["داعية", "استغفار", "توبة"],
    correctPhraseIds: ["وَاسْتَغْفِرْ لِذَنبِكَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "هل يُطالَب الداعية بالعدل مع المخالف؟",
    themeEnglish: "Is a caller required to be just with opponents?",
    description: "شخصية الداعية - العدل",
    tags: ["داعية", "عدل", "إنصاف"],
    correctPhraseIds: ["وَلَا يَجْرِمَنَّكُمْ شَنَآنُ قَوْمٍ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يتعامل الداعية مع أهل الكتاب وغير المسلمين؟",
    themeEnglish: "How does a caller deal with People of the Book and non-Muslims?",
    description: "شخصية الداعية - الحوار",
    tags: ["داعية", "حوار", "أهل الكتاب"],
    correctPhraseIds: ["إِلَّا بِالَّتِي هِيَ أَحْسَنُ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما الموقف من عناد الناس بعد البيان؟",
    themeEnglish: "What is the stance when people are stubborn after clarification?",
    description: "شخصية الداعية - البلاغ",
    tags: ["داعية", "بلاغ", "عناد"],
    correctPhraseIds: ["فَمَا أَرْسَلْنَاكَ عَلَيْهِمْ حَفِيظًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف ينظر الداعية إلى نفسه وسط العمل؟",
    themeEnglish: "How does a caller view themselves during work?",
    description: "شخصية الداعية - التواضع",
    tags: ["داعية", "فضل", "تواضع"],
    correctPhraseIds: ["وَلَوْلَا فَضْلُ اللَّهِ عَلَيْكُمْ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما صفة التثبّت في نقل الأخبار عند الداعية؟",
    themeEnglish: "What is the quality of verification in transmitting news for a caller?",
    description: "شخصية الداعية - التثبت",
    tags: ["داعية", "تثبت", "خبر"],
    correctPhraseIds: ["فَتَبَيَّنُوا"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "كيف يوازن الداعية بين أسرته ودعوته؟",
    themeEnglish: "How does a caller balance family and calling?",
    description: "شخصية الداعية - الأسرة",
    tags: ["داعية", "أسرة", "أهل"],
    correctPhraseIds: ["وَأْمُرْ أَهْلَكَ بِالصَّلَاةِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما صفة الجهاد بالبيان؟",
    themeEnglish: "What is the quality of striving through speech?",
    description: "شخصية الداعية - الجهاد البياني",
    tags: ["داعية", "جهاد", "قرآن"],
    correctPhraseIds: ["وَجَاهِدْهُم بِهِ جِهَادًا كَبِيرًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يجمع الداعية بين العلم والعمل والصبر؟",
    themeEnglish: "How does a caller combine knowledge, action, and patience?",
    description: "شخصية الداعية - التكامل",
    tags: ["داعية", "علم", "عمل", "صبر"],
    correctPhraseIds: ["وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما حدود مسؤولية الداعية عن هداية الناس؟",
    themeEnglish: "What are the limits of a caller's responsibility for guiding people?",
    description: "شخصية الداعية - الهداية",
    tags: ["داعية", "هداية", "مسؤولية"],
    correctPhraseIds: ["إِنَّكَ لَا تَهْدِي مَنْ أَحْبَبْتَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما أهمية معرفة الداعية بسنن الله في الدعوات؟",
    themeEnglish: "What is the importance of a caller knowing Allah's ways in calling?",
    description: "شخصية الداعية - السنن",
    tags: ["داعية", "سنن", "تاريخ"],
    correctPhraseIds: ["قَدْ خَلَتْ مِن قَبْلِكُمْ سُنَنٌ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يحافظ الداعية على الأمل رغم الشدائد؟",
    themeEnglish: "How does a caller maintain hope despite hardships?",
    description: "شخصية الداعية - الأمل",
    tags: ["داعية", "أمل", "رجاء"],
    correctPhraseIds: ["وَلَا تَيْأَسُوا مِن رَّوْحِ اللَّهِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما دلالة التواضع في مخاطبة العصاة؟",
    themeEnglish: "What is the significance of humility when addressing sinners?",
    description: "شخصية الداعية - مخاطبة العصاة",
    tags: ["داعية", "تواضع", "رحمة"],
    correctPhraseIds: ["يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف ينظّم الداعية وقته بين القيام والعمل؟",
    themeEnglish: "How does a caller organize time between worship and work?",
    description: "شخصية الداعية - تنظيم الوقت",
    tags: ["داعية", "وقت", "قيام"],
    correctPhraseIds: ["نَاشِئَةَ اللَّيْلِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما علامة خضوع الداعية لأمر الله في الشدة والرخاء؟",
    themeEnglish: "What is the sign of a caller's submission to Allah's command in ease and hardship?",
    description: "شخصية الداعية - الخضوع",
    tags: ["داعية", "خضوع", "تسليم"],
    correctPhraseIds: ["إِنَّ صَلَاتِي وَنُسُكِي وَمَحْيَايَ وَمَمَاتِي لِلَّهِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يتعامل الداعية مع ضعف نفسه وذلاتها؟",
    themeEnglish: "How does a caller deal with personal weaknesses and mistakes?",
    description: "شخصية الداعية - الضعف البشري",
    tags: ["داعية", "ضعف", "دعاء"],
    correctPhraseIds: ["رَبَّنَا لَا تُؤَاخِذْنَا إِن نَّسِينَا أَوْ أَخْطَأْنَا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما صفة العدل في تقييم الناس؟",
    themeEnglish: "What is the quality of justice in evaluating people?",
    description: "شخصية الداعية - العدل في التقييم",
    tags: ["داعية", "عدل", "تقوى"],
    correctPhraseIds: ["إِنَّ أَكْرَمَكُمْ عِندَ اللَّهِ أَتْقَاكُمْ"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "كيف يكون الداعية رفيقًا بالمخالف في مسائل الاجتهاد؟",
    themeEnglish: "How is a caller gentle with those who differ in matters of interpretation?",
    description: "شخصية الداعية - الرفق بالمخالف",
    tags: ["داعية", "رفق", "اجتهاد"],
    correctPhraseIds: ["فَاتَّقُوا اللَّهَ مَا اسْتَطَعْتُمْ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يظهر تعظيم الداعية للقرآن؟",
    themeEnglish: "How does a caller show reverence for the Quran?",
    description: "شخصية الداعية - تعظيم القرآن",
    tags: ["داعية", "قرآن", "ترتيل"],
    correctPhraseIds: ["وَرَتِّلِ الْقُرْآنَ تَرْتِيلًا"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "ما حدود الإنكار باللسان؟",
    themeEnglish: "What are the limits of verbal criticism?",
    description: "شخصية الداعية - الإنكار",
    tags: ["داعية", "إنكار", "أسلوب"],
    correctPhraseIds: ["وَجَادِلْهُم بِالَّتِي هِيَ أَحْسَنُ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ماذا عن تربية الداعية لنفسه على مراقبة الله؟",
    themeEnglish: "What about a caller training themselves on consciousness of Allah?",
    description: "شخصية الداعية - المراقبة",
    tags: ["داعية", "مراقبة", "خشية"],
    correctPhraseIds: ["أَلَمْ يَعْلَمْ بِأَنَّ اللَّهَ يَرَىٰ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يحفظ الداعية قلبه من الكِبر العلمي؟",
    themeEnglish: "How does a caller protect their heart from intellectual arrogance?",
    description: "شخصية الداعية - الكبر العلمي",
    tags: ["داعية", "كبر", "تواضع"],
    correctPhraseIds: ["فَلَا تُزَكُّوا أَنفُسَكُمْ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما صفة الشمول في دعوة الداعية؟",
    themeEnglish: "What is the quality of comprehensiveness in a caller's invitation?",
    description: "شخصية الداعية - الشمول",
    tags: ["داعية", "شمول", "عموم"],
    correctPhraseIds: ["إِنِّي رَسُولُ اللَّهِ إِلَيْكُمْ جَمِيعًا"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يراعي الداعية تفاوت العقول؟",
    themeEnglish: "How does a caller consider varying intellects?",
    description: "شخصية الداعية - مراعاة العقول",
    tags: ["داعية", "عقول", "خطاب"],
    correctPhraseIds: ["وَمَا يَعْقِلُهَا إِلَّا الْعَالِمُونَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما علامة التوكل في قلب الداعية؟",
    themeEnglish: "What is the sign of trust in a caller's heart?",
    description: "شخصية الداعية - التوكل",
    tags: ["داعية", "توكل", "إيمان"],
    correctPhraseIds: ["وَعَلَى اللَّهِ فَتَوَكَّلُوا"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "كيف يتعامل الداعية مع الابتلاءات الفردية؟",
    themeEnglish: "How does a caller deal with personal trials?",
    description: "شخصية الداعية - الابتلاء",
    tags: ["داعية", "ابتلاء", "صبر"],
    correctPhraseIds: ["إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "ما موقع الدعوة من مفهوم الأمة الخيّرة؟",
    themeEnglish: "What is the position of calling in the concept of the best nation?",
    description: "شخصية الداعية - الأمة الخيرة",
    tags: ["داعية", "أمة", "أمر بالمعروف"],
    correctPhraseIds: ["كُنتُمْ خَيْرَ أُمَّةٍ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يربّي الداعية نفسه على الصدق في الوعود؟",
    themeEnglish: "How does a caller train themselves on truthfulness in promises?",
    description: "شخصية الداعية - الوفاء",
    tags: ["داعية", "وعد", "عهد"],
    correctPhraseIds: ["وَأَوْفُوا بِالْعَهْدِ"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "ما مظهر العناية بالضعفاء في خطاب الداعية؟",
    themeEnglish: "What is the manifestation of caring for the weak in a caller's discourse?",
    description: "شخصية الداعية - العناية بالضعفاء",
    tags: ["داعية", "ضعفاء", "يتيم"],
    correctPhraseIds: ["فَأَمَّا الْيَتِيمَ فَلَا تَقْهَرْ"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "كيف ينبغي للداعية أن يتعامل مع المال؟",
    themeEnglish: "How should a caller deal with money?",
    description: "شخصية الداعية - المال",
    tags: ["داعية", "مال", "أمانة"],
    correctPhraseIds: ["وَلَا تَأْكُلُوا أَمْوَالَكُم بَيْنَكُم بِالْبَاطِلِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما معيار تقديم الأهم على المهم في أولويات الدعوة؟",
    themeEnglish: "What is the criterion for prioritizing in calling?",
    description: "شخصية الداعية - الأولويات",
    tags: ["داعية", "أولويات", "توحيد"],
    correctPhraseIds: ["إِلَّا لِيَعْبُدُونِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما صفة الأمانة في حمل العلم؟",
    themeEnglish: "What is the quality of trust in carrying knowledge?",
    description: "شخصية الداعية - الأمانة العلمية",
    tags: ["داعية", "أمانة", "علم"],
    correctPhraseIds: ["إِنَّا عَرَضْنَا الْأَمَانَةَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يحذر الداعية من تحريف الكلم؟",
    themeEnglish: "How does a caller beware of distorting words?",
    description: "شخصية الداعية - التحريف",
    tags: ["داعية", "تحريف", "أمانة"],
    correctPhraseIds: ["يُحَرِّفُونَ الْكَلِمَ عَن مَّوَاضِعِهِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما صفة الشفافية في الاعتراف بالخطأ؟",
    themeEnglish: "What is the quality of transparency in admitting mistakes?",
    description: "شخصية الداعية - الاعتراف بالخطأ",
    tags: ["داعية", "خطأ", "اعتراف"],
    correctPhraseIds: ["رَبَّنَا ظَلَمْنَا أَنفُسَنَا"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "كيف يكون الداعية سمحًا في المعاملة؟",
    themeEnglish: "How is a caller lenient in dealings?",
    description: "شخصية الداعية - السماحة",
    tags: ["داعية", "سماحة", "عفو"],
    correctPhraseIds: ["خُذِ الْعَفْوَ وَأْمُرْ بِالْعُرْفِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما موقف الداعية من الدنيا وزينتها؟",
    themeEnglish: "What is a caller's stance toward worldly life and its adornment?",
    description: "شخصية الداعية - الدنيا",
    tags: ["داعية", "دنيا", "زهد"],
    correctPhraseIds: ["مَتَاعُ الْغُرُورِ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يربّي الداعية قلبه على محبة الآخرة؟",
    themeEnglish: "How does a caller nurture love for the Hereafter?",
    description: "شخصية الداعية - الآخرة",
    tags: ["داعية", "آخرة", "محبة"],
    correctPhraseIds: ["وَالْآخِرَةُ خَيْرٌ وَأَبْقَىٰ"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "ما صفة الاستقامة العملية للداعية؟",
    themeEnglish: "What is the quality of practical steadfastness for a caller?",
    description: "شخصية الداعية - الاستقامة",
    tags: ["داعية", "استقامة", "ثبات"],
    correctPhraseIds: ["فَاسْتَقِمْ كَمَا أُمِرْتَ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "كيف يتعامل الداعية مع وساوس النفس والشيطان؟",
    themeEnglish: "How does a caller deal with whispers of the self and Satan?",
    description: "شخصية الداعية - الوساوس",
    tags: ["داعية", "وسوسة", "استعاذة"],
    correctPhraseIds: ["أَعُوذُ بِرَبِّ النَّاسِ"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "ما أهمية حفظ الجوارح للداعية؟",
    themeEnglish: "What is the importance of guarding one's limbs for a caller?",
    description: "شخصية الداعية - حفظ الجوارح",
    tags: ["داعية", "جوارح", "بصر"],
    correctPhraseIds: ["يَغُضُّوا مِنْ أَبْصَارِهِمْ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما علاقة الدعوة بالأخوة الإيمانية؟",
    themeEnglish: "What is the relationship between calling and faithful brotherhood?",
    description: "شخصية الداعية - الأخوة",
    tags: ["داعية", "أخوة", "إيمان"],
    correctPhraseIds: ["إِنَّمَا الْمُؤْمِنُونَ إِخْوَةٌ"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "كيف يضبط الداعية حديثه عن نيات الآخرين؟",
    themeEnglish: "How does a caller control speech about others' intentions?",
    description: "شخصية الداعية - الظن",
    tags: ["داعية", "ظن", "نية"],
    correctPhraseIds: ["إِنَّ بَعْضَ الظَّنِّ إِثْمٌ"],
    difficulty: 2,
    category: "thematic",
  },
  {
    theme: "ما صفة الإحسان في كل مناحي حياة الداعية؟",
    themeEnglish: "What is the quality of excellence in all aspects of a caller's life?",
    description: "شخصية الداعية - الإحسان",
    tags: ["داعية", "إحسان", "إتقان"],
    correctPhraseIds: ["إِنَّ اللَّهَ يُحِبُّ الْمُحْسِنِينَ"],
    difficulty: 1,
    category: "thematic",
  },
  {
    theme: "ما موقف الداعية من أهل المعاصي في المجتمع؟",
    themeEnglish: "What is a caller's stance toward sinners in society?",
    description: "شخصية الداعية - أهل المعاصي",
    tags: ["داعية", "تعاون", "بر"],
    correctPhraseIds: ["وَتَعَاوَنُوا عَلَى الْبِرِّ وَالتَّقْوَىٰ"],
    difficulty: 2,
    category: "thematic",
  },
];

async function seedDaiyahQuestions() {
  console.log("🕌 Starting to seed Da'iyah personality questions...\n");
  
  let successCount = 0;
  let errorCount = 0;
  const total = daiyahQuestions.length;
  
  for (let i = 0; i < total; i++) {
    const q = daiyahQuestions[i];
    try {
      await db.insert(questionBanks).values({
        theme: q.theme,
        themeEnglish: q.themeEnglish,
        description: q.description,
        tags: q.tags,
        correctPhraseIds: q.correctPhraseIds,
        difficulty: q.difficulty,
        category: q.category,
      });
      successCount++;
      console.log(`✅ [${i + 1}/${total}] Added: ${q.correctPhraseIds[0].substring(0, 30)}...`);
    } catch (error: any) {
      errorCount++;
      console.error(`❌ [${i + 1}/${total}] Failed: ${q.theme.substring(0, 40)}... - ${error.message}`);
    }
  }
  
  console.log(`\n📊 Summary:`);
  console.log(`   ✅ Successfully added: ${successCount} questions`);
  console.log(`   ❌ Errors: ${errorCount}`);
  console.log(`\n🕌 Da'iyah personality questions seeding complete!`);
}

seedDaiyahQuestions()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("Fatal error:", error);
    process.exit(1);
  });
